/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineConfigBindingFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializePipelineConfigBinding, serializeUpdateBindingRequest, type PipelineConfigBinding, type ResultProblem, type UpdateBindingRequest } from '../../../../models/index.js';
// @ts-ignore
import { ReconcileRequestBuilderRequestsMetadata, type ReconcileRequestBuilder } from './reconcile/index.js';
// @ts-ignore
import { StatusRequestBuilderRequestsMetadata, type StatusRequestBuilder } from './status/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/binding
 */
export interface BindingRequestBuilder extends BaseRequestBuilder<BindingRequestBuilder> {
    /**
     * The reconcile property
     */
    get reconcile(): ReconcileRequestBuilder;
    /**
     * The status property
     */
    get status(): StatusRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineConfigBinding>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineConfigBinding | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineConfigBinding>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     patch(body: UpdateBindingRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineConfigBinding | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: UpdateBindingRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BindingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/binding";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BindingRequestBuilderNavigationMetadata: Record<Exclude<keyof BindingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    reconcile: {
        requestsMetadata: ReconcileRequestBuilderRequestsMetadata,
    },
    status: {
        requestsMetadata: StatusRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BindingRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BindingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineConfigBindingFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: BindingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineConfigBindingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateBindingRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
