/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineSourceFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeCreatePipelineSourceRequest, serializePipelineSource, type CreatePipelineSourceRequest, type PipelineSource, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type WithSourceItemRequestBuilder, WithSourceItemRequestBuilderNavigationMetadata, WithSourceItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/sources
 */
export interface SourcesRequestBuilder extends BaseRequestBuilder<SourcesRequestBuilder> {
    /**
     * Gets an item from the OlvePipelines.api.pipelines.item.sources.item collection
     * @param sourceId Unique identifier of the item
     * @returns {WithSourceItemRequestBuilder}
     */
     bySourceId(sourceId: Guid) : WithSourceItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineSource[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineSource[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineSource>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: CreatePipelineSourceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineSource | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePipelineSourceRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SourcesRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/sources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof SourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySourceId: {
        requestsMetadata: WithSourceItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithSourceItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["sourceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SourcesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPipelineSourceFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineSourceFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePipelineSourceRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
