/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPromotionStateFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializePromotionState, serializeSetPromotionRequest, type PromotionState, type ResultProblem, type SetPromotionRequest } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/processing-steps/{stepId}/promotion
 */
export interface PromotionRequestBuilder extends BaseRequestBuilder<PromotionRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PromotionState>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PromotionState | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PromotionState>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     put(body: SetPromotionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PromotionState | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: SetPromotionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PromotionRequestBuilderUriTemplate = "{+baseurl}/api/processing-steps/{stepId}/promotion";
/**
 * Metadata for all the requests in the request builder.
 */
export const PromotionRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PromotionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPromotionStateFromDiscriminatorValue,
    },
    put: {
        uriTemplate: PromotionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPromotionStateFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSetPromotionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
