/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProcessingStepFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type ProcessingStep, type ResultProblem } from '../../../../../models/index.js';
// @ts-ignore
import { ScriptRequestBuilderRequestsMetadata, type ScriptRequestBuilder } from './script/index.js';
// @ts-ignore
import { type VerificationsRequestBuilder, VerificationsRequestBuilderNavigationMetadata, VerificationsRequestBuilderRequestsMetadata } from './verifications/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/processing/{processingId}
 */
export interface WithProcessingItemRequestBuilder extends BaseRequestBuilder<WithProcessingItemRequestBuilder> {
    /**
     * The script property
     */
    get script(): ScriptRequestBuilder;
    /**
     * The verifications property
     */
    get verifications(): VerificationsRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProcessingStep>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProcessingStep | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithProcessingItemRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/processing/{processingId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithProcessingItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithProcessingItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    script: {
        requestsMetadata: ScriptRequestBuilderRequestsMetadata,
    },
    verifications: {
        requestsMetadata: VerificationsRequestBuilderRequestsMetadata,
        navigationMetadata: VerificationsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithProcessingItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithProcessingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: WithProcessingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProcessingStepFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
