/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultProblemFromDiscriminatorValue, createSourceBundleFromDiscriminatorValue, type ResultProblem, type SourceBundle } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger/sourcing
 */
export interface SourcingRequestBuilder extends BaseRequestBuilder<SourcingRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SourceBundle>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SourceBundle | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SourcingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger/sourcing";
/**
 * Metadata for all the requests in the request builder.
 */
export const SourcingRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SourcingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSourceBundleFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
