/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBundleItemRequestBuilder, WithBundleItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/artifact-bundles
 */
export interface ArtifactBundlesRequestBuilder extends BaseRequestBuilder<ArtifactBundlesRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesApi.api.artifactBundles.item collection
     * @param bundleId Unique identifier of the item
     * @returns {WithBundleItemRequestBuilder}
     */
     byBundleId(bundleId: string) : WithBundleItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ArtifactBundlesRequestBuilderUriTemplate = "{+baseurl}/api/artifact-bundles";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ArtifactBundlesRequestBuilderNavigationMetadata: Record<Exclude<keyof ArtifactBundlesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBundleId: {
        requestsMetadata: WithBundleItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["bundleId"],
    },
};
/* tslint:enable */
/* eslint-enable */
