/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineConfigBindingFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializePipelineConfigBinding, serializeSetDeployTriggerRequest, type PipelineConfigBinding, type ResultProblem, type SetDeployTriggerRequest } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/binding/deploy-trigger
 */
export interface DeployTriggerRequestBuilder extends BaseRequestBuilder<DeployTriggerRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineConfigBinding>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     patch(body: SetDeployTriggerRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineConfigBinding | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: SetDeployTriggerRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DeployTriggerRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/binding/deploy-trigger";
/**
 * Metadata for all the requests in the request builder.
 */
export const DeployTriggerRequestBuilderRequestsMetadata: RequestsMetadata = {
    patch: {
        uriTemplate: DeployTriggerRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineConfigBindingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSetDeployTriggerRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
