{{- if .Values.garage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-garage
  labels:
    app: {{ .Release.Name }}-garage
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-garage
  ports:
    - name: s3
      port: 3900
      targetPort: s3
{{- end }}
