/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineBuilderFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeCreatePipelineBuilderRequest, serializePipelineBuilder, type CreatePipelineBuilderRequest, type PipelineBuilder, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type WithBuilderItemRequestBuilder, WithBuilderItemRequestBuilderNavigationMetadata, WithBuilderItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/builders
 */
export interface BuildersRequestBuilder extends BaseRequestBuilder<BuildersRequestBuilder> {
    /**
     * Gets an item from the OlvePipelines.api.pipelines.item.builders.item collection
     * @param builderId Unique identifier of the item
     * @returns {WithBuilderItemRequestBuilder}
     */
     byBuilderId(builderId: Guid) : WithBuilderItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineBuilder[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineBuilder[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineBuilder>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: CreatePipelineBuilderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineBuilder | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePipelineBuilderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BuildersRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/builders";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BuildersRequestBuilderNavigationMetadata: Record<Exclude<keyof BuildersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBuilderId: {
        requestsMetadata: WithBuilderItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithBuilderItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["builderId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BuildersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BuildersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPipelineBuilderFromDiscriminatorValue,
    },
    post: {
        uriTemplate: BuildersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineBuilderFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePipelineBuilderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
