/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineConfigBindingFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeCreatePipelineWithRepoRequest, serializePipelineConfigBinding, type CreatePipelineWithRepoRequest, type PipelineConfigBinding, type ResultProblem } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/with-repo
 */
export interface WithRepoRequestBuilder extends BaseRequestBuilder<WithRepoRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineConfigBinding>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: CreatePipelineWithRepoRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineConfigBinding | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreatePipelineWithRepoRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithRepoRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/with-repo";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithRepoRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithRepoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineConfigBindingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreatePipelineWithRepoRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
