/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithStepItemRequestBuilder, WithStepItemRequestBuilderNavigationMetadata, WithStepItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/production-steps
 */
export interface ProductionStepsRequestBuilder extends BaseRequestBuilder<ProductionStepsRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesClient.api.productionSteps.item collection
     * @param stepId Unique identifier of the item
     * @returns {WithStepItemRequestBuilder}
     */
     byStepId(stepId: string) : WithStepItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProductionStepsRequestBuilderUriTemplate = "{+baseurl}/api/production-steps";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProductionStepsRequestBuilderNavigationMetadata: Record<Exclude<keyof ProductionStepsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byStepId: {
        requestsMetadata: WithStepItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithStepItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["stepId"],
    },
};
/* tslint:enable */
/* eslint-enable */
