/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProductionStepFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeCreateProductionStepRequest, serializeProductionStep, type CreateProductionStepRequest, type ProductionStep, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/production
 */
export interface ProductionRequestBuilder extends BaseRequestBuilder<ProductionRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProductionStep[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProductionStep[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProductionStep>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: CreateProductionStepRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProductionStep | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateProductionStepRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProductionRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/production";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProductionRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProductionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createProductionStepFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ProductionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProductionStepFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateProductionStepRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
