/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobGroupProcessingJobGroupFromDiscriminatorValue, createJobGroupProductionJobGroupFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, createWebhookRequestFromDiscriminatorValue, deserializeIntoJobGroupProcessingJobGroup, deserializeIntoJobGroupProductionJobGroup, deserializeIntoWebhookRequest, serializeJobGroupProcessingJobGroup, serializeJobGroupProductionJobGroup, serializeWebhookRequest, type JobGroupProcessingJobGroup, type JobGroupProductionJobGroup, type ResultProblem, type WebhookRequest } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobGroupProcessingJobGroup | JobGroupProductionJobGroup}
 */
// @ts-ignore
export function createJobGroupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobGroup;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookRequest | WithTriggerPostRequestBodyMember1}
 */
// @ts-ignore
export function createWithTriggerPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithTriggerPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithTriggerPostRequestBodyMember1}
 */
// @ts-ignore
export function createWithTriggerPostRequestBodyMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithTriggerPostRequestBodyMember1;
}
/**
 * The deserialization information for the current model
 * @param JobGroup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobGroup(jobGroup: Partial<JobGroupProcessingJobGroup | JobGroupProductionJobGroup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoJobGroupProcessingJobGroup(jobGroup as JobGroupProcessingJobGroup),
        ...deserializeIntoJobGroupProductionJobGroup(jobGroup as JobGroupProductionJobGroup),
    }
}
/**
 * The deserialization information for the current model
 * @param WithTriggerPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithTriggerPostRequestBody(withTriggerPostRequestBody: Partial<WebhookRequest | WithTriggerPostRequestBodyMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoWebhookRequest(withTriggerPostRequestBody as WebhookRequest),
        ...deserializeIntoWithTriggerPostRequestBodyMember1(withTriggerPostRequestBody as WithTriggerPostRequestBodyMember1),
    }
}
/**
 * The deserialization information for the current model
 * @param WithTriggerPostRequestBodyMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithTriggerPostRequestBodyMember1(withTriggerPostRequestBodyMember1: Partial<WithTriggerPostRequestBodyMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export type JobGroup = JobGroupProcessingJobGroup | JobGroupProductionJobGroup;
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobGroup The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobGroup(writer: SerializationWriter, jobGroup: Partial<JobGroupProcessingJobGroup | JobGroupProductionJobGroup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeJobGroupProcessingJobGroup(writer, jobGroup as JobGroupProcessingJobGroup);
    serializeJobGroupProductionJobGroup(writer, jobGroup as JobGroupProductionJobGroup);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithTriggerPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithTriggerPostRequestBody(writer: SerializationWriter, withTriggerPostRequestBody: Partial<WebhookRequest | WithTriggerPostRequestBodyMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeWebhookRequest(writer, withTriggerPostRequestBody as WebhookRequest);
    serializeWithTriggerPostRequestBodyMember1(writer, withTriggerPostRequestBody as WithTriggerPostRequestBodyMember1);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithTriggerPostRequestBodyMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithTriggerPostRequestBodyMember1(writer: SerializationWriter, withTriggerPostRequestBodyMember1: Partial<WithTriggerPostRequestBodyMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withTriggerPostRequestBodyMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(withTriggerPostRequestBodyMember1.additionalData);
}
/**
 * Builds and executes requests for operations under /api/webhooks/{triggerId}
 */
export interface WithTriggerItemRequestBuilder extends BaseRequestBuilder<WithTriggerItemRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobGroupProcessingJobGroup | JobGroupProductionJobGroup>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: WebhookRequest | WithTriggerPostRequestBodyMember1, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobGroupProcessingJobGroup | JobGroupProductionJobGroup | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WebhookRequest | WithTriggerPostRequestBodyMember1, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export type WithTriggerPostRequestBody = WebhookRequest | WithTriggerPostRequestBodyMember1;
export interface WithTriggerPostRequestBodyMember1 extends AdditionalDataHolder, Parsable {
}
/**
 * Uri template for the request builder.
 */
export const WithTriggerItemRequestBuilderUriTemplate = "{+baseurl}/api/webhooks/{triggerId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTriggerItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithTriggerItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobGroupFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWithTriggerPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
