/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTriggerItemRequestBuilder, WithTriggerItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/triggers
 */
export interface TriggersRequestBuilder extends BaseRequestBuilder<TriggersRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesApi.api.triggers.item collection
     * @param triggerId Unique identifier of the item
     * @returns {WithTriggerItemRequestBuilder}
     */
     byTriggerId(triggerId: string) : WithTriggerItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TriggersRequestBuilderUriTemplate = "{+baseurl}/api/triggers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TriggersRequestBuilderNavigationMetadata: Record<Exclude<keyof TriggersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTriggerId: {
        requestsMetadata: WithTriggerItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["triggerId"],
    },
};
/* tslint:enable */
/* eslint-enable */
