/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineDocumentFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type PipelineDocument, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/document
 */
export interface DocumentRequestBuilder extends BaseRequestBuilder<DocumentRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineDocument>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineDocument | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DocumentRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/document";
/**
 * Metadata for all the requests in the request builder.
 */
export const DocumentRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DocumentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineDocumentFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
