/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BuildingRequestBuilderRequestsMetadata, type BuildingRequestBuilder } from './building/index.js';
// @ts-ignore
import { ProcessingRequestBuilderNavigationMetadata, type ProcessingRequestBuilder } from './processing/index.js';
// @ts-ignore
import { SourcingRequestBuilderRequestsMetadata, type SourcingRequestBuilder } from './sourcing/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger
 */
export interface TriggerRequestBuilder extends BaseRequestBuilder<TriggerRequestBuilder> {
    /**
     * The building property
     */
    get building(): BuildingRequestBuilder;
    /**
     * The processing property
     */
    get processing(): ProcessingRequestBuilder;
    /**
     * The sourcing property
     */
    get sourcing(): SourcingRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TriggerRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TriggerRequestBuilderNavigationMetadata: Record<Exclude<keyof TriggerRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    building: {
        requestsMetadata: BuildingRequestBuilderRequestsMetadata,
    },
    processing: {
        navigationMetadata: ProcessingRequestBuilderNavigationMetadata,
    },
    sourcing: {
        requestsMetadata: SourcingRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
