/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ProcessingRequestBuilderRequestsMetadata, type ProcessingRequestBuilder } from './processing/index.js';
// @ts-ignore
import { ProductionRequestBuilderRequestsMetadata, type ProductionRequestBuilder } from './production/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger
 */
export interface TriggerRequestBuilder extends BaseRequestBuilder<TriggerRequestBuilder> {
    /**
     * The processing property
     */
    get processing(): ProcessingRequestBuilder;
    /**
     * The production property
     */
    get production(): ProductionRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TriggerRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TriggerRequestBuilderNavigationMetadata: Record<Exclude<keyof TriggerRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    processing: {
        requestsMetadata: ProcessingRequestBuilderRequestsMetadata,
    },
    production: {
        requestsMetadata: ProductionRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
