/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultProblemFromDiscriminatorValue, createScriptBuilderFromDiscriminatorValue, serializeScriptBuilder, serializeSetScriptBuilderRequest, type ResultProblem, type ScriptBuilder, type SetScriptBuilderRequest } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/builders/{builderId}/script
 */
export interface ScriptRequestBuilder extends BaseRequestBuilder<ScriptRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ScriptBuilder>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ScriptBuilder | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ScriptBuilder>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     put(body: SetScriptBuilderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ScriptBuilder | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: SetScriptBuilderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ScriptRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/builders/{builderId}/script";
/**
 * Metadata for all the requests in the request builder.
 */
export const ScriptRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ScriptRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: ScriptRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScriptBuilderFromDiscriminatorValue,
    },
    put: {
        uriTemplate: ScriptRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createScriptBuilderFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSetScriptBuilderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
