/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GithubRequestBuilderRequestsMetadata, type GithubRequestBuilder } from './github/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/webhooks/binding/{bindingId}
 */
export interface WithBindingItemRequestBuilder extends BaseRequestBuilder<WithBindingItemRequestBuilder> {
    /**
     * The github property
     */
    get github(): GithubRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithBindingItemRequestBuilderUriTemplate = "{+baseurl}/api/webhooks/binding/{bindingId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithBindingItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithBindingItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    github: {
        requestsMetadata: GithubRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
