/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBindingItemRequestBuilder, WithBindingItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/webhooks/binding
 */
export interface BindingRequestBuilder extends BaseRequestBuilder<BindingRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesClient.api.webhooks.binding.item collection
     * @param bindingId Unique identifier of the item
     * @returns {WithBindingItemRequestBuilder}
     */
     byBindingId(bindingId: string) : WithBindingItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const BindingRequestBuilderUriTemplate = "{+baseurl}/api/webhooks/binding";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BindingRequestBuilderNavigationMetadata: Record<Exclude<keyof BindingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBindingId: {
        navigationMetadata: WithBindingItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["bindingId"],
    },
};
/* tslint:enable */
/* eslint-enable */
