/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type Job, type ResultProblem } from '../../models/index.js';
// @ts-ignore
import { JobsItemRequestBuilderNavigationMetadata, JobsItemRequestBuilderRequestsMetadata, type JobsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { QueueRequestBuilderRequestsMetadata, type QueueRequestBuilder } from './queue/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/jobs
 */
export interface JobsRequestBuilder extends BaseRequestBuilder<JobsRequestBuilder> {
    /**
     * The queue property
     */
    get queue(): QueueRequestBuilder;
    /**
     * Gets an item from the OlvePipelinesClient.api.jobs.item collection
     * @param id Unique identifier of the item
     * @returns {JobsItemRequestBuilder}
     */
     byId(id: string) : JobsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Job[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Job[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JobsRequestBuilderUriTemplate = "{+baseurl}/api/jobs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobsRequestBuilderNavigationMetadata: Record<Exclude<keyof JobsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: JobsItemRequestBuilderRequestsMetadata,
        navigationMetadata: JobsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    queue: {
        requestsMetadata: QueueRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const JobsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JobsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createJobFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
