/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobProcessingJobFromDiscriminatorValue, createJobProductionJobFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, deserializeIntoJobProcessingJob, deserializeIntoJobProductionJob, serializeJobProcessingJob, serializeJobProductionJob, type JobProcessingJob, type JobProductionJob, type ResultProblem } from '../../models/index.js';
// @ts-ignore
import { JobsItemRequestBuilderNavigationMetadata, JobsItemRequestBuilderRequestsMetadata, type JobsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { QueueRequestBuilderRequestsMetadata, type QueueRequestBuilder } from './queue/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobProcessingJob | JobProductionJob}
 */
// @ts-ignore
export function createJobFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJob;
}
/**
 * The deserialization information for the current model
 * @param Job The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJob(job: Partial<JobProcessingJob | JobProductionJob> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoJobProcessingJob(job as JobProcessingJob),
        ...deserializeIntoJobProductionJob(job as JobProductionJob),
    }
}
export type Job = JobProcessingJob | JobProductionJob;
/**
 * Builds and executes requests for operations under /api/jobs
 */
export interface JobsRequestBuilder extends BaseRequestBuilder<JobsRequestBuilder> {
    /**
     * The queue property
     */
    get queue(): QueueRequestBuilder;
    /**
     * Gets an item from the OlvePipelinesClient.api.jobs.item collection
     * @param id Unique identifier of the item
     * @returns {JobsItemRequestBuilder}
     */
     byId(id: string) : JobsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<(JobProcessingJob | JobProductionJob)[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<(JobProcessingJob | JobProductionJob)[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Job The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJob(writer: SerializationWriter, job: Partial<JobProcessingJob | JobProductionJob> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeJobProcessingJob(writer, job as JobProcessingJob);
    serializeJobProductionJob(writer, job as JobProductionJob);
}
/**
 * Uri template for the request builder.
 */
export const JobsRequestBuilderUriTemplate = "{+baseurl}/api/jobs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobsRequestBuilderNavigationMetadata: Record<Exclude<keyof JobsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: JobsItemRequestBuilderRequestsMetadata,
        navigationMetadata: JobsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    queue: {
        requestsMetadata: QueueRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const JobsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JobsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createJobFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
