/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithAssetItemRequestBuilder, WithAssetItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /download
 */
export interface DownloadRequestBuilder extends BaseRequestBuilder<DownloadRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesClient.download.item collection
     * @param asset Unique identifier of the item
     * @returns {WithAssetItemRequestBuilder}
     */
     byAsset(asset: string) : WithAssetItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DownloadRequestBuilderUriTemplate = "{+baseurl}/download";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DownloadRequestBuilderNavigationMetadata: Record<Exclude<keyof DownloadRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAsset: {
        requestsMetadata: WithAssetItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["asset"],
    },
};
/* tslint:enable */
/* eslint-enable */
