/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

export interface ArtifactBundle extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The sourceBundleId property
     */
    sourceBundleId?: Guid | null;
    /**
     * The status property
     */
    status?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ArtifactBundle}
 */
// @ts-ignore
export function createArtifactBundleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoArtifactBundle;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePipelineBuilderRequest}
 */
// @ts-ignore
export function createCreatePipelineBuilderRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePipelineBuilderRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreatePipelineSourceRequest}
 */
// @ts-ignore
export function createCreatePipelineSourceRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreatePipelineSourceRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateProcessingStepRequest}
 */
// @ts-ignore
export function createCreateProcessingStepRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateProcessingStepRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateVerificationRequest}
 */
// @ts-ignore
export function createCreateVerificationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateVerificationRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GitHubSource}
 */
// @ts-ignore
export function createGitHubSourceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGitHubSource;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HardcodedSource_files}
 */
// @ts-ignore
export function createHardcodedSource_filesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHardcodedSource_files;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {HardcodedSource}
 */
// @ts-ignore
export function createHardcodedSourceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoHardcodedSource;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PipelineBuilder}
 */
// @ts-ignore
export function createPipelineBuilderFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPipelineBuilder;
}
export interface CreatePipelineBuilderRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Pipeline}
 */
// @ts-ignore
export function createPipelineFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPipeline;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PipelineSource}
 */
// @ts-ignore
export function createPipelineSourceFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPipelineSource;
}
export interface CreatePipelineSourceRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProcessingStep}
 */
// @ts-ignore
export function createProcessingStepFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProcessingStep;
}
export interface CreateProcessingStepRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultProblem}
 */
// @ts-ignore
export function createResultProblemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultProblem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScriptBuilder}
 */
// @ts-ignore
export function createScriptBuilderFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScriptBuilder;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScriptProcessing}
 */
// @ts-ignore
export function createScriptProcessingFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScriptProcessing;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ScriptVerification}
 */
// @ts-ignore
export function createScriptVerificationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoScriptVerification;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetGitHubSourceRequest}
 */
// @ts-ignore
export function createSetGitHubSourceRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetGitHubSourceRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetHardcodedSourceRequest_files}
 */
// @ts-ignore
export function createSetHardcodedSourceRequest_filesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetHardcodedSourceRequest_files;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetHardcodedSourceRequest}
 */
// @ts-ignore
export function createSetHardcodedSourceRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetHardcodedSourceRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetScriptBuilderRequest}
 */
// @ts-ignore
export function createSetScriptBuilderRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetScriptBuilderRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetScriptProcessingRequest}
 */
// @ts-ignore
export function createSetScriptProcessingRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetScriptProcessingRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetScriptVerificationRequest}
 */
// @ts-ignore
export function createSetScriptVerificationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetScriptVerificationRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SourceBundle}
 */
// @ts-ignore
export function createSourceBundleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSourceBundle;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Verification}
 */
// @ts-ignore
export function createVerificationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVerification;
}
export interface CreateVerificationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * The deserialization information for the current model
 * @param ArtifactBundle The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoArtifactBundle(artifactBundle: Partial<ArtifactBundle> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { artifactBundle.createdAt = n.getDateValue(); },
        "id": n => { artifactBundle.id = n.getGuidValue(); },
        "pipelineId": n => { artifactBundle.pipelineId = n.getGuidValue(); },
        "sourceBundleId": n => { artifactBundle.sourceBundleId = n.getGuidValue(); },
        "status": n => { artifactBundle.status = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePipelineBuilderRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePipelineBuilderRequest(createPipelineBuilderRequest: Partial<CreatePipelineBuilderRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createPipelineBuilderRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreatePipelineSourceRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreatePipelineSourceRequest(createPipelineSourceRequest: Partial<CreatePipelineSourceRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createPipelineSourceRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateProcessingStepRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateProcessingStepRequest(createProcessingStepRequest: Partial<CreateProcessingStepRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createProcessingStepRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateVerificationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateVerificationRequest(createVerificationRequest: Partial<CreateVerificationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createVerificationRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GitHubSource The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGitHubSource(gitHubSource: Partial<GitHubSource> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "branch": n => { gitHubSource.branch = n.getStringValue(); },
        "owner": n => { gitHubSource.owner = n.getStringValue(); },
        "repository": n => { gitHubSource.repository = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param HardcodedSource The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHardcodedSource(hardcodedSource: Partial<HardcodedSource> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "files": n => { hardcodedSource.files = n.getObjectValue<HardcodedSource_files>(createHardcodedSource_filesFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param HardcodedSource_files The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoHardcodedSource_files(hardcodedSource_files: Partial<HardcodedSource_files> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param Pipeline The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPipeline(pipeline: Partial<Pipeline> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { pipeline.id = n.getGuidValue(); },
        "name": n => { pipeline.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PipelineBuilder The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPipelineBuilder(pipelineBuilder: Partial<PipelineBuilder> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { pipelineBuilder.id = n.getGuidValue(); },
        "name": n => { pipelineBuilder.name = n.getStringValue(); },
        "pipelineId": n => { pipelineBuilder.pipelineId = n.getGuidValue(); },
        "type": n => { pipelineBuilder.type = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PipelineSource The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPipelineSource(pipelineSource: Partial<PipelineSource> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { pipelineSource.id = n.getGuidValue(); },
        "name": n => { pipelineSource.name = n.getStringValue(); },
        "pipelineId": n => { pipelineSource.pipelineId = n.getGuidValue(); },
        "type": n => { pipelineSource.type = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProcessingStep The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProcessingStep(processingStep: Partial<ProcessingStep> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { processingStep.id = n.getGuidValue(); },
        "name": n => { processingStep.name = n.getStringValue(); },
        "pipelineId": n => { processingStep.pipelineId = n.getGuidValue(); },
        "type": n => { processingStep.type = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultProblem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultProblem(resultProblem: Partial<ResultProblem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exceptionSummary": n => { resultProblem.exceptionSummary = n.getStringValue(); },
        "message": n => { resultProblem.messageEscaped = n.getStringValue(); },
        "severity": n => { resultProblem.severity = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "source": n => { resultProblem.source = n.getStringValue(); },
        "tags": n => { resultProblem.tags = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ScriptBuilder The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScriptBuilder(scriptBuilder: Partial<ScriptBuilder> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "script": n => { scriptBuilder.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ScriptProcessing The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScriptProcessing(scriptProcessing: Partial<ScriptProcessing> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "script": n => { scriptProcessing.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ScriptVerification The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoScriptVerification(scriptVerification: Partial<ScriptVerification> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "script": n => { scriptVerification.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetGitHubSourceRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetGitHubSourceRequest(setGitHubSourceRequest: Partial<SetGitHubSourceRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "branch": n => { setGitHubSourceRequest.branch = n.getStringValue(); },
        "owner": n => { setGitHubSourceRequest.owner = n.getStringValue(); },
        "repository": n => { setGitHubSourceRequest.repository = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetHardcodedSourceRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetHardcodedSourceRequest(setHardcodedSourceRequest: Partial<SetHardcodedSourceRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "files": n => { setHardcodedSourceRequest.files = n.getObjectValue<SetHardcodedSourceRequest_files>(createSetHardcodedSourceRequest_filesFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetHardcodedSourceRequest_files The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetHardcodedSourceRequest_files(setHardcodedSourceRequest_files: Partial<SetHardcodedSourceRequest_files> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param SetScriptBuilderRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetScriptBuilderRequest(setScriptBuilderRequest: Partial<SetScriptBuilderRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "script": n => { setScriptBuilderRequest.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetScriptProcessingRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetScriptProcessingRequest(setScriptProcessingRequest: Partial<SetScriptProcessingRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "script": n => { setScriptProcessingRequest.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetScriptVerificationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetScriptVerificationRequest(setScriptVerificationRequest: Partial<SetScriptVerificationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "script": n => { setScriptVerificationRequest.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SourceBundle The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSourceBundle(sourceBundle: Partial<SourceBundle> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { sourceBundle.createdAt = n.getDateValue(); },
        "id": n => { sourceBundle.id = n.getGuidValue(); },
        "pipelineId": n => { sourceBundle.pipelineId = n.getGuidValue(); },
        "status": n => { sourceBundle.status = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Verification The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVerification(verification: Partial<Verification> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { verification.id = n.getGuidValue(); },
        "name": n => { verification.name = n.getStringValue(); },
        "processingStepId": n => { verification.processingStepId = n.getGuidValue(); },
        "type": n => { verification.type = n.getNumberValue(); },
    }
}
export interface GitHubSource extends AdditionalDataHolder, Parsable {
    /**
     * The branch property
     */
    branch?: string | null;
    /**
     * The owner property
     */
    owner?: string | null;
    /**
     * The repository property
     */
    repository?: string | null;
}
export interface HardcodedSource extends AdditionalDataHolder, Parsable {
    /**
     * The files property
     */
    files?: HardcodedSource_files | null;
}
export interface HardcodedSource_files extends AdditionalDataHolder, Parsable {
}
export interface Pipeline extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface PipelineBuilder extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The type property
     */
    type?: number | null;
}
export interface PipelineSource extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The type property
     */
    type?: number | null;
}
export interface ProcessingStep extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The type property
     */
    type?: number | null;
}
export interface ResultProblem extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The exceptionSummary property
     */
    exceptionSummary?: string | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The severity property
     */
    severity?: UntypedNode | null;
    /**
     * The source property
     */
    source?: string | null;
    /**
     * The tags property
     */
    tags?: string[] | null;
}
export interface ScriptBuilder extends AdditionalDataHolder, Parsable {
    /**
     * The script property
     */
    script?: string | null;
}
export interface ScriptProcessing extends AdditionalDataHolder, Parsable {
    /**
     * The script property
     */
    script?: string | null;
}
export interface ScriptVerification extends AdditionalDataHolder, Parsable {
    /**
     * The script property
     */
    script?: string | null;
}
/**
 * Serializes information the current object
 * @param ArtifactBundle The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeArtifactBundle(writer: SerializationWriter, artifactBundle: Partial<ArtifactBundle> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!artifactBundle || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", artifactBundle.createdAt);
    writer.writeGuidValue("id", artifactBundle.id);
    writer.writeGuidValue("pipelineId", artifactBundle.pipelineId);
    writer.writeGuidValue("sourceBundleId", artifactBundle.sourceBundleId);
    writer.writeNumberValue("status", artifactBundle.status);
    writer.writeAdditionalData(artifactBundle.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePipelineBuilderRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePipelineBuilderRequest(writer: SerializationWriter, createPipelineBuilderRequest: Partial<CreatePipelineBuilderRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPipelineBuilderRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createPipelineBuilderRequest.name);
    writer.writeAdditionalData(createPipelineBuilderRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreatePipelineSourceRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreatePipelineSourceRequest(writer: SerializationWriter, createPipelineSourceRequest: Partial<CreatePipelineSourceRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createPipelineSourceRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createPipelineSourceRequest.name);
    writer.writeAdditionalData(createPipelineSourceRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateProcessingStepRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateProcessingStepRequest(writer: SerializationWriter, createProcessingStepRequest: Partial<CreateProcessingStepRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createProcessingStepRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createProcessingStepRequest.name);
    writer.writeAdditionalData(createProcessingStepRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateVerificationRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateVerificationRequest(writer: SerializationWriter, createVerificationRequest: Partial<CreateVerificationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createVerificationRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createVerificationRequest.name);
    writer.writeAdditionalData(createVerificationRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param GitHubSource The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGitHubSource(writer: SerializationWriter, gitHubSource: Partial<GitHubSource> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!gitHubSource || isSerializingDerivedType) { return; }
    writer.writeStringValue("branch", gitHubSource.branch);
    writer.writeStringValue("owner", gitHubSource.owner);
    writer.writeStringValue("repository", gitHubSource.repository);
    writer.writeAdditionalData(gitHubSource.additionalData);
}
/**
 * Serializes information the current object
 * @param HardcodedSource The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHardcodedSource(writer: SerializationWriter, hardcodedSource: Partial<HardcodedSource> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!hardcodedSource || isSerializingDerivedType) { return; }
    writer.writeObjectValue<HardcodedSource_files>("files", hardcodedSource.files, serializeHardcodedSource_files);
    writer.writeAdditionalData(hardcodedSource.additionalData);
}
/**
 * Serializes information the current object
 * @param HardcodedSource_files The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeHardcodedSource_files(writer: SerializationWriter, hardcodedSource_files: Partial<HardcodedSource_files> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!hardcodedSource_files || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(hardcodedSource_files.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Pipeline The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePipeline(writer: SerializationWriter, pipeline: Partial<Pipeline> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pipeline || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", pipeline.id);
    writer.writeStringValue("name", pipeline.name);
    writer.writeAdditionalData(pipeline.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PipelineBuilder The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePipelineBuilder(writer: SerializationWriter, pipelineBuilder: Partial<PipelineBuilder> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pipelineBuilder || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", pipelineBuilder.id);
    writer.writeStringValue("name", pipelineBuilder.name);
    writer.writeGuidValue("pipelineId", pipelineBuilder.pipelineId);
    writer.writeNumberValue("type", pipelineBuilder.type);
    writer.writeAdditionalData(pipelineBuilder.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PipelineSource The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePipelineSource(writer: SerializationWriter, pipelineSource: Partial<PipelineSource> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pipelineSource || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", pipelineSource.id);
    writer.writeStringValue("name", pipelineSource.name);
    writer.writeGuidValue("pipelineId", pipelineSource.pipelineId);
    writer.writeNumberValue("type", pipelineSource.type);
    writer.writeAdditionalData(pipelineSource.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProcessingStep The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProcessingStep(writer: SerializationWriter, processingStep: Partial<ProcessingStep> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!processingStep || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", processingStep.id);
    writer.writeStringValue("name", processingStep.name);
    writer.writeGuidValue("pipelineId", processingStep.pipelineId);
    writer.writeNumberValue("type", processingStep.type);
    writer.writeAdditionalData(processingStep.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultProblem The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultProblem(writer: SerializationWriter, resultProblem: Partial<ResultProblem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultProblem || isSerializingDerivedType) { return; }
    writer.writeStringValue("exceptionSummary", resultProblem.exceptionSummary);
    writer.writeStringValue("message", resultProblem.messageEscaped);
    writer.writeObjectValue("severity", resultProblem.severity);
    writer.writeStringValue("source", resultProblem.source);
    writer.writeCollectionOfPrimitiveValues<string>("tags", resultProblem.tags);
    writer.writeAdditionalData(resultProblem.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ScriptBuilder The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScriptBuilder(writer: SerializationWriter, scriptBuilder: Partial<ScriptBuilder> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!scriptBuilder || isSerializingDerivedType) { return; }
    writer.writeStringValue("script", scriptBuilder.script);
    writer.writeAdditionalData(scriptBuilder.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ScriptProcessing The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScriptProcessing(writer: SerializationWriter, scriptProcessing: Partial<ScriptProcessing> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!scriptProcessing || isSerializingDerivedType) { return; }
    writer.writeStringValue("script", scriptProcessing.script);
    writer.writeAdditionalData(scriptProcessing.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ScriptVerification The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeScriptVerification(writer: SerializationWriter, scriptVerification: Partial<ScriptVerification> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!scriptVerification || isSerializingDerivedType) { return; }
    writer.writeStringValue("script", scriptVerification.script);
    writer.writeAdditionalData(scriptVerification.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetGitHubSourceRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetGitHubSourceRequest(writer: SerializationWriter, setGitHubSourceRequest: Partial<SetGitHubSourceRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setGitHubSourceRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("branch", setGitHubSourceRequest.branch);
    writer.writeStringValue("owner", setGitHubSourceRequest.owner);
    writer.writeStringValue("repository", setGitHubSourceRequest.repository);
    writer.writeAdditionalData(setGitHubSourceRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetHardcodedSourceRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetHardcodedSourceRequest(writer: SerializationWriter, setHardcodedSourceRequest: Partial<SetHardcodedSourceRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setHardcodedSourceRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SetHardcodedSourceRequest_files>("files", setHardcodedSourceRequest.files, serializeSetHardcodedSourceRequest_files);
    writer.writeAdditionalData(setHardcodedSourceRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetHardcodedSourceRequest_files The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetHardcodedSourceRequest_files(writer: SerializationWriter, setHardcodedSourceRequest_files: Partial<SetHardcodedSourceRequest_files> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setHardcodedSourceRequest_files || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(setHardcodedSourceRequest_files.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetScriptBuilderRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetScriptBuilderRequest(writer: SerializationWriter, setScriptBuilderRequest: Partial<SetScriptBuilderRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setScriptBuilderRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("script", setScriptBuilderRequest.script);
    writer.writeAdditionalData(setScriptBuilderRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetScriptProcessingRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetScriptProcessingRequest(writer: SerializationWriter, setScriptProcessingRequest: Partial<SetScriptProcessingRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setScriptProcessingRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("script", setScriptProcessingRequest.script);
    writer.writeAdditionalData(setScriptProcessingRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetScriptVerificationRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetScriptVerificationRequest(writer: SerializationWriter, setScriptVerificationRequest: Partial<SetScriptVerificationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setScriptVerificationRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("script", setScriptVerificationRequest.script);
    writer.writeAdditionalData(setScriptVerificationRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SourceBundle The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSourceBundle(writer: SerializationWriter, sourceBundle: Partial<SourceBundle> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!sourceBundle || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", sourceBundle.createdAt);
    writer.writeGuidValue("id", sourceBundle.id);
    writer.writeGuidValue("pipelineId", sourceBundle.pipelineId);
    writer.writeNumberValue("status", sourceBundle.status);
    writer.writeAdditionalData(sourceBundle.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Verification The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVerification(writer: SerializationWriter, verification: Partial<Verification> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!verification || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", verification.id);
    writer.writeStringValue("name", verification.name);
    writer.writeGuidValue("processingStepId", verification.processingStepId);
    writer.writeNumberValue("type", verification.type);
    writer.writeAdditionalData(verification.additionalData);
}
export interface SetGitHubSourceRequest extends AdditionalDataHolder, Parsable {
    /**
     * The branch property
     */
    branch?: string | null;
    /**
     * The owner property
     */
    owner?: string | null;
    /**
     * The repository property
     */
    repository?: string | null;
}
export interface SetHardcodedSourceRequest extends AdditionalDataHolder, Parsable {
    /**
     * The files property
     */
    files?: SetHardcodedSourceRequest_files | null;
}
export interface SetHardcodedSourceRequest_files extends AdditionalDataHolder, Parsable {
}
export interface SetScriptBuilderRequest extends AdditionalDataHolder, Parsable {
    /**
     * The script property
     */
    script?: string | null;
}
export interface SetScriptProcessingRequest extends AdditionalDataHolder, Parsable {
    /**
     * The script property
     */
    script?: string | null;
}
export interface SetScriptVerificationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The script property
     */
    script?: string | null;
}
export interface SourceBundle extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The status property
     */
    status?: number | null;
}
export interface Verification extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The processingStepId property
     */
    processingStepId?: Guid | null;
    /**
     * The type property
     */
    type?: number | null;
}
/* tslint:enable */
/* eslint-enable */
