/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

export interface ArtifactBundle extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The status property
     */
    status?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ArtifactBundle}
 */
// @ts-ignore
export function createArtifactBundleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoArtifactBundle;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateProcessingStepRequest}
 */
// @ts-ignore
export function createCreateProcessingStepRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateProcessingStepRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateProductionStepRequest}
 */
// @ts-ignore
export function createCreateProductionStepRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateProductionStepRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateTriggerRequest}
 */
// @ts-ignore
export function createCreateTriggerRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateTriggerRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IdOfArtifactBundle}
 */
// @ts-ignore
export function createIdOfArtifactBundleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIdOfArtifactBundle;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobGroupProcessingJobGroup}
 */
// @ts-ignore
export function createJobGroupProcessingJobGroupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobGroupProcessingJobGroup;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobGroupProductionJobGroup}
 */
// @ts-ignore
export function createJobGroupProductionJobGroupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobGroupProductionJobGroup;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobProcessingJob_processingResultMember1 | Result}
 */
// @ts-ignore
export function createJobProcessingJob_processingResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobProcessingJob_processingResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobProcessingJob_processingResultMember1}
 */
// @ts-ignore
export function createJobProcessingJob_processingResultMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobProcessingJob_processingResultMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobProcessingJob}
 */
// @ts-ignore
export function createJobProcessingJobFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobProcessingJob;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobProductionJob}
 */
// @ts-ignore
export function createJobProductionJobFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobProductionJob;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusCancelled}
 */
// @ts-ignore
export function createJobStatusCancelledFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatusCancelled;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusDone}
 */
// @ts-ignore
export function createJobStatusDoneFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatusDone;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusFailed}
 */
// @ts-ignore
export function createJobStatusFailedFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatusFailed;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled}
 */
// @ts-ignore
export function createJobStatusFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatus;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusInProgress}
 */
// @ts-ignore
export function createJobStatusInProgressFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatusInProgress;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusObsolete}
 */
// @ts-ignore
export function createJobStatusObsoleteFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatusObsolete;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobStatusScheduled}
 */
// @ts-ignore
export function createJobStatusScheduledFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobStatusScheduled;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Pipeline}
 */
// @ts-ignore
export function createPipelineFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPipeline;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProcessingJobKey}
 */
// @ts-ignore
export function createProcessingJobKeyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProcessingJobKey;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProcessingStep}
 */
// @ts-ignore
export function createProcessingStepFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProcessingStep;
}
export interface CreateProcessingStepRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The order property
     */
    order?: UntypedNode | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductionJobKey}
 */
// @ts-ignore
export function createProductionJobKeyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductionJobKey;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductionStep}
 */
// @ts-ignore
export function createProductionStepFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductionStep;
}
export interface CreateProductionStepRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Result}
 */
// @ts-ignore
export function createResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResultProblem}
 */
// @ts-ignore
export function createResultProblemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResultProblem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetSecretRequest}
 */
// @ts-ignore
export function createSetSecretRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetSecretRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetStepConfigurationRequest_environmentVariables}
 */
// @ts-ignore
export function createSetStepConfigurationRequest_environmentVariablesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetStepConfigurationRequest_environmentVariables;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SetStepConfigurationRequest}
 */
// @ts-ignore
export function createSetStepConfigurationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSetStepConfigurationRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StepConfiguration_environmentVariables}
 */
// @ts-ignore
export function createStepConfiguration_environmentVariablesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStepConfiguration_environmentVariables;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StepConfiguration}
 */
// @ts-ignore
export function createStepConfigurationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStepConfiguration;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Trigger}
 */
// @ts-ignore
export function createTriggerFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTrigger;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TriggerProcessingRequest}
 */
// @ts-ignore
export function createTriggerProcessingRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTriggerProcessingRequest;
}
export interface CreateTriggerRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The target property
     */
    target?: TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget}
 */
// @ts-ignore
export function createTriggerTargetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTriggerTarget;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TriggerTargetProcessingTriggerTarget}
 */
// @ts-ignore
export function createTriggerTargetProcessingTriggerTargetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTriggerTargetProcessingTriggerTarget;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TriggerTargetProductionTriggerTarget}
 */
// @ts-ignore
export function createTriggerTargetProductionTriggerTargetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTriggerTargetProductionTriggerTarget;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateOrderRequest}
 */
// @ts-ignore
export function createUpdateOrderRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateOrderRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IdOfArtifactBundle | WebhookRequest_artifactBundleIdMember1}
 */
// @ts-ignore
export function createWebhookRequest_artifactBundleIdFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookRequest_artifactBundleId;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookRequest_artifactBundleIdMember1}
 */
// @ts-ignore
export function createWebhookRequest_artifactBundleIdMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookRequest_artifactBundleIdMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WebhookRequest}
 */
// @ts-ignore
export function createWebhookRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWebhookRequest;
}
/**
 * The deserialization information for the current model
 * @param ArtifactBundle The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoArtifactBundle(artifactBundle: Partial<ArtifactBundle> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { artifactBundle.createdAt = n.getDateValue(); },
        "id": n => { artifactBundle.id = n.getGuidValue(); },
        "pipelineId": n => { artifactBundle.pipelineId = n.getGuidValue(); },
        "status": n => { artifactBundle.status = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateProcessingStepRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateProcessingStepRequest(createProcessingStepRequest: Partial<CreateProcessingStepRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createProcessingStepRequest.name = n.getStringValue(); },
        "order": n => { createProcessingStepRequest.order = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateProductionStepRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateProductionStepRequest(createProductionStepRequest: Partial<CreateProductionStepRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createProductionStepRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateTriggerRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateTriggerRequest(createTriggerRequest: Partial<CreateTriggerRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createTriggerRequest.name = n.getStringValue(); },
        "target": n => { createTriggerRequest.target = n.getObjectValue<TriggerTargetProcessingTriggerTarget>(createTriggerTargetProcessingTriggerTargetFromDiscriminatorValue) ?? n.getObjectValue<TriggerTargetProductionTriggerTarget>(createTriggerTargetProductionTriggerTargetFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param IdOfArtifactBundle The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIdOfArtifactBundle(idOfArtifactBundle: Partial<IdOfArtifactBundle> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param JobGroupProcessingJobGroup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobGroupProcessingJobGroup(jobGroupProcessingJobGroup: Partial<JobGroupProcessingJobGroup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "artifactBundleId": n => { jobGroupProcessingJobGroup.artifactBundleId = n.getGuidValue(); },
        "createdAt": n => { jobGroupProcessingJobGroup.createdAt = n.getDateValue(); },
        "id": n => { jobGroupProcessingJobGroup.id = n.getGuidValue(); },
        "pipelineId": n => { jobGroupProcessingJobGroup.pipelineId = n.getGuidValue(); },
        "processingStepId": n => { jobGroupProcessingJobGroup.processingStepId = n.getGuidValue(); },
        "$type": n => { jobGroupProcessingJobGroup.type = n.getEnumValue<JobGroupProcessingJobGroup_Type>(JobGroupProcessingJobGroup_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobGroupProductionJobGroup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobGroupProductionJobGroup(jobGroupProductionJobGroup: Partial<JobGroupProductionJobGroup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "artifactBundleId": n => { jobGroupProductionJobGroup.artifactBundleId = n.getGuidValue(); },
        "createdAt": n => { jobGroupProductionJobGroup.createdAt = n.getDateValue(); },
        "id": n => { jobGroupProductionJobGroup.id = n.getGuidValue(); },
        "pipelineId": n => { jobGroupProductionJobGroup.pipelineId = n.getGuidValue(); },
        "$type": n => { jobGroupProductionJobGroup.type = n.getEnumValue<JobGroupProductionJobGroup_Type>(JobGroupProductionJobGroup_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobProcessingJob The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobProcessingJob(jobProcessingJob: Partial<JobProcessingJob> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "artifactBundleId": n => { jobProcessingJob.artifactBundleId = n.getGuidValue(); },
        "createdAt": n => { jobProcessingJob.createdAt = n.getDateValue(); },
        "id": n => { jobProcessingJob.id = n.getGuidValue(); },
        "jobGroupId": n => { jobProcessingJob.jobGroupId = n.getGuidValue(); },
        "jobKey": n => { jobProcessingJob.jobKey = n.getObjectValue<ProcessingJobKey>(createProcessingJobKeyFromDiscriminatorValue); },
        "pipelineId": n => { jobProcessingJob.pipelineId = n.getGuidValue(); },
        "processingResult": n => { jobProcessingJob.processingResult = n.getObjectValue<JobProcessingJob_processingResultMember1>(createJobProcessingJob_processingResultMember1FromDiscriminatorValue) ?? n.getObjectValue<Result>(createResultFromDiscriminatorValue); },
        "processingStepId": n => { jobProcessingJob.processingStepId = n.getGuidValue(); },
        "status": n => { jobProcessingJob.status = n.getObjectValue<JobStatusCancelled>(createJobStatusCancelledFromDiscriminatorValue) ?? n.getObjectValue<JobStatusDone>(createJobStatusDoneFromDiscriminatorValue) ?? n.getObjectValue<JobStatusFailed>(createJobStatusFailedFromDiscriminatorValue) ?? n.getObjectValue<JobStatusInProgress>(createJobStatusInProgressFromDiscriminatorValue) ?? n.getObjectValue<JobStatusObsolete>(createJobStatusObsoleteFromDiscriminatorValue) ?? n.getObjectValue<JobStatusScheduled>(createJobStatusScheduledFromDiscriminatorValue); },
        "$type": n => { jobProcessingJob.type = n.getEnumValue<JobProcessingJob_Type>(JobProcessingJob_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobProcessingJob_processingResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobProcessingJob_processingResult(jobProcessingJob_processingResult: Partial<JobProcessingJob_processingResultMember1 | Result> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoJobProcessingJob_processingResultMember1(jobProcessingJob_processingResult as JobProcessingJob_processingResultMember1),
        ...deserializeIntoResult(jobProcessingJob_processingResult as Result),
    }
}
/**
 * The deserialization information for the current model
 * @param JobProcessingJob_processingResultMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobProcessingJob_processingResultMember1(jobProcessingJob_processingResultMember1: Partial<JobProcessingJob_processingResultMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param JobProductionJob The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobProductionJob(jobProductionJob: Partial<JobProductionJob> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { jobProductionJob.createdAt = n.getDateValue(); },
        "id": n => { jobProductionJob.id = n.getGuidValue(); },
        "jobGroupId": n => { jobProductionJob.jobGroupId = n.getGuidValue(); },
        "jobKey": n => { jobProductionJob.jobKey = n.getObjectValue<ProductionJobKey>(createProductionJobKeyFromDiscriminatorValue); },
        "pipelineId": n => { jobProductionJob.pipelineId = n.getGuidValue(); },
        "productionStepId": n => { jobProductionJob.productionStepId = n.getGuidValue(); },
        "status": n => { jobProductionJob.status = n.getObjectValue<JobStatusCancelled>(createJobStatusCancelledFromDiscriminatorValue) ?? n.getObjectValue<JobStatusDone>(createJobStatusDoneFromDiscriminatorValue) ?? n.getObjectValue<JobStatusFailed>(createJobStatusFailedFromDiscriminatorValue) ?? n.getObjectValue<JobStatusInProgress>(createJobStatusInProgressFromDiscriminatorValue) ?? n.getObjectValue<JobStatusObsolete>(createJobStatusObsoleteFromDiscriminatorValue) ?? n.getObjectValue<JobStatusScheduled>(createJobStatusScheduledFromDiscriminatorValue); },
        "$type": n => { jobProductionJob.type = n.getEnumValue<JobProductionJob_Type>(JobProductionJob_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatus The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatus(jobStatus: Partial<JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoJobStatusCancelled(jobStatus as JobStatusCancelled),
        ...deserializeIntoJobStatusDone(jobStatus as JobStatusDone),
        ...deserializeIntoJobStatusFailed(jobStatus as JobStatusFailed),
        ...deserializeIntoJobStatusInProgress(jobStatus as JobStatusInProgress),
        ...deserializeIntoJobStatusObsolete(jobStatus as JobStatusObsolete),
        ...deserializeIntoJobStatusScheduled(jobStatus as JobStatusScheduled),
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatusCancelled The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatusCancelled(jobStatusCancelled: Partial<JobStatusCancelled> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "cancelledAt": n => { jobStatusCancelled.cancelledAt = n.getDateValue(); },
        "startedAt": n => { jobStatusCancelled.startedAt = n.getDateValue(); },
        "$type": n => { jobStatusCancelled.type = n.getEnumValue<JobStatusCancelled_Type>(JobStatusCancelled_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatusDone The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatusDone(jobStatusDone: Partial<JobStatusDone> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "completedAt": n => { jobStatusDone.completedAt = n.getDateValue(); },
        "startedAt": n => { jobStatusDone.startedAt = n.getDateValue(); },
        "$type": n => { jobStatusDone.type = n.getEnumValue<JobStatusDone_Type>(JobStatusDone_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatusFailed The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatusFailed(jobStatusFailed: Partial<JobStatusFailed> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "failedAt": n => { jobStatusFailed.failedAt = n.getDateValue(); },
        "reason": n => { jobStatusFailed.reason = n.getStringValue(); },
        "startedAt": n => { jobStatusFailed.startedAt = n.getDateValue(); },
        "$type": n => { jobStatusFailed.type = n.getEnumValue<JobStatusFailed_Type>(JobStatusFailed_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatusInProgress The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatusInProgress(jobStatusInProgress: Partial<JobStatusInProgress> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "startedAt": n => { jobStatusInProgress.startedAt = n.getDateValue(); },
        "$type": n => { jobStatusInProgress.type = n.getEnumValue<JobStatusInProgress_Type>(JobStatusInProgress_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatusObsolete The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatusObsolete(jobStatusObsolete: Partial<JobStatusObsolete> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "supersedingJobId": n => { jobStatusObsolete.supersedingJobId = n.getGuidValue(); },
        "$type": n => { jobStatusObsolete.type = n.getEnumValue<JobStatusObsolete_Type>(JobStatusObsolete_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param JobStatusScheduled The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobStatusScheduled(jobStatusScheduled: Partial<JobStatusScheduled> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "$type": n => { jobStatusScheduled.type = n.getEnumValue<JobStatusScheduled_Type>(JobStatusScheduled_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param Pipeline The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPipeline(pipeline: Partial<Pipeline> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { pipeline.id = n.getGuidValue(); },
        "name": n => { pipeline.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProcessingJobKey The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProcessingJobKey(processingJobKey: Partial<ProcessingJobKey> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "pipelineId": n => { processingJobKey.pipelineId = n.getGuidValue(); },
        "processingStepId": n => { processingJobKey.processingStepId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProcessingStep The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProcessingStep(processingStep: Partial<ProcessingStep> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { processingStep.id = n.getGuidValue(); },
        "name": n => { processingStep.name = n.getStringValue(); },
        "order": n => { processingStep.order = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "pipelineId": n => { processingStep.pipelineId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProductionJobKey The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductionJobKey(productionJobKey: Partial<ProductionJobKey> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "pipelineId": n => { productionJobKey.pipelineId = n.getGuidValue(); },
        "productionStepId": n => { productionJobKey.productionStepId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProductionStep The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductionStep(productionStep: Partial<ProductionStep> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { productionStep.id = n.getGuidValue(); },
        "name": n => { productionStep.name = n.getStringValue(); },
        "pipelineId": n => { productionStep.pipelineId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Result The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResult(result: Partial<Result> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "failed": n => { result.failed = n.getBooleanValue(); },
        "problems": n => { result.problems = n.getCollectionOfObjectValues<ResultProblem>(createResultProblemFromDiscriminatorValue); },
        "succeeded": n => { result.succeeded = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ResultProblem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResultProblem(resultProblem: Partial<ResultProblem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exceptionSummary": n => { resultProblem.exceptionSummary = n.getStringValue(); },
        "message": n => { resultProblem.messageEscaped = n.getStringValue(); },
        "severity": n => { resultProblem.severity = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "source": n => { resultProblem.source = n.getStringValue(); },
        "tags": n => { resultProblem.tags = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetSecretRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetSecretRequest(setSecretRequest: Partial<SetSecretRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "value": n => { setSecretRequest.value = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetStepConfigurationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetStepConfigurationRequest(setStepConfigurationRequest: Partial<SetStepConfigurationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "environmentVariables": n => { setStepConfigurationRequest.environmentVariables = n.getObjectValue<SetStepConfigurationRequest_environmentVariables>(createSetStepConfigurationRequest_environmentVariablesFromDiscriminatorValue); },
        "image": n => { setStepConfigurationRequest.image = n.getStringValue(); },
        "script": n => { setStepConfigurationRequest.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SetStepConfigurationRequest_environmentVariables The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSetStepConfigurationRequest_environmentVariables(setStepConfigurationRequest_environmentVariables: Partial<SetStepConfigurationRequest_environmentVariables> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param StepConfiguration The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStepConfiguration(stepConfiguration: Partial<StepConfiguration> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "environmentVariables": n => { stepConfiguration.environmentVariables = n.getObjectValue<StepConfiguration_environmentVariables>(createStepConfiguration_environmentVariablesFromDiscriminatorValue); },
        "image": n => { stepConfiguration.image = n.getStringValue(); },
        "script": n => { stepConfiguration.script = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param StepConfiguration_environmentVariables The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStepConfiguration_environmentVariables(stepConfiguration_environmentVariables: Partial<StepConfiguration_environmentVariables> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param Trigger The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTrigger(trigger: Partial<Trigger> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { trigger.createdAt = n.getDateValue(); },
        "id": n => { trigger.id = n.getGuidValue(); },
        "name": n => { trigger.name = n.getStringValue(); },
        "pipelineId": n => { trigger.pipelineId = n.getGuidValue(); },
        "secret": n => { trigger.secret = n.getStringValue(); },
        "target": n => { trigger.target = n.getObjectValue<TriggerTargetProcessingTriggerTarget>(createTriggerTargetProcessingTriggerTargetFromDiscriminatorValue) ?? n.getObjectValue<TriggerTargetProductionTriggerTarget>(createTriggerTargetProductionTriggerTargetFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param TriggerProcessingRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTriggerProcessingRequest(triggerProcessingRequest: Partial<TriggerProcessingRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "artifactBundleId": n => { triggerProcessingRequest.artifactBundleId = n.getGuidValue(); },
        "processingStepId": n => { triggerProcessingRequest.processingStepId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TriggerTarget The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTriggerTarget(triggerTarget: Partial<TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoTriggerTargetProcessingTriggerTarget(triggerTarget as TriggerTargetProcessingTriggerTarget),
        ...deserializeIntoTriggerTargetProductionTriggerTarget(triggerTarget as TriggerTargetProductionTriggerTarget),
    }
}
/**
 * The deserialization information for the current model
 * @param TriggerTargetProcessingTriggerTarget The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTriggerTargetProcessingTriggerTarget(triggerTargetProcessingTriggerTarget: Partial<TriggerTargetProcessingTriggerTarget> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "processingStepId": n => { triggerTargetProcessingTriggerTarget.processingStepId = n.getGuidValue(); },
        "$type": n => { triggerTargetProcessingTriggerTarget.type = n.getEnumValue<TriggerTargetProcessingTriggerTarget_Type>(TriggerTargetProcessingTriggerTarget_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param TriggerTargetProductionTriggerTarget The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTriggerTargetProductionTriggerTarget(triggerTargetProductionTriggerTarget: Partial<TriggerTargetProductionTriggerTarget> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "$type": n => { triggerTargetProductionTriggerTarget.type = n.getEnumValue<TriggerTargetProductionTriggerTarget_Type>(TriggerTargetProductionTriggerTarget_TypeObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateOrderRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateOrderRequest(updateOrderRequest: Partial<UpdateOrderRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "order": n => { updateOrderRequest.order = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookRequest(webhookRequest: Partial<WebhookRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "artifactBundleId": n => { webhookRequest.artifactBundleId = n.getObjectValue<IdOfArtifactBundle>(createIdOfArtifactBundleFromDiscriminatorValue) ?? n.getObjectValue<WebhookRequest_artifactBundleIdMember1>(createWebhookRequest_artifactBundleIdMember1FromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookRequest_artifactBundleId The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookRequest_artifactBundleId(webhookRequest_artifactBundleId: Partial<IdOfArtifactBundle | WebhookRequest_artifactBundleIdMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoIdOfArtifactBundle(webhookRequest_artifactBundleId as IdOfArtifactBundle),
        ...deserializeIntoWebhookRequest_artifactBundleIdMember1(webhookRequest_artifactBundleId as WebhookRequest_artifactBundleIdMember1),
    }
}
/**
 * The deserialization information for the current model
 * @param WebhookRequest_artifactBundleIdMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWebhookRequest_artifactBundleIdMember1(webhookRequest_artifactBundleIdMember1: Partial<WebhookRequest_artifactBundleIdMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface IdOfArtifactBundle extends AdditionalDataHolder, Parsable {
}
export interface JobGroupProcessingJobGroup extends AdditionalDataHolder, Parsable {
    /**
     * The artifactBundleId property
     */
    artifactBundleId?: Guid | null;
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The processingStepId property
     */
    processingStepId?: Guid | null;
    /**
     * The Type property
     */
    type?: JobGroupProcessingJobGroup_Type | null;
}
export type JobGroupProcessingJobGroup_Type = (typeof JobGroupProcessingJobGroup_TypeObject)[keyof typeof JobGroupProcessingJobGroup_TypeObject];
export interface JobGroupProductionJobGroup extends AdditionalDataHolder, Parsable {
    /**
     * The artifactBundleId property
     */
    artifactBundleId?: Guid | null;
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The Type property
     */
    type?: JobGroupProductionJobGroup_Type | null;
}
export type JobGroupProductionJobGroup_Type = (typeof JobGroupProductionJobGroup_TypeObject)[keyof typeof JobGroupProductionJobGroup_TypeObject];
export interface JobProcessingJob extends AdditionalDataHolder, Parsable {
    /**
     * The artifactBundleId property
     */
    artifactBundleId?: Guid | null;
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The jobGroupId property
     */
    jobGroupId?: Guid | null;
    /**
     * The jobKey property
     */
    jobKey?: ProcessingJobKey | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The processingResult property
     */
    processingResult?: JobProcessingJob_processingResultMember1 | Result | null;
    /**
     * The processingStepId property
     */
    processingStepId?: Guid | null;
    /**
     * The status property
     */
    status?: JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled | null;
    /**
     * The Type property
     */
    type?: JobProcessingJob_Type | null;
}
export type JobProcessingJob_processingResult = JobProcessingJob_processingResultMember1 | Result;
export interface JobProcessingJob_processingResultMember1 extends AdditionalDataHolder, Parsable {
}
export type JobProcessingJob_Type = (typeof JobProcessingJob_TypeObject)[keyof typeof JobProcessingJob_TypeObject];
export interface JobProductionJob extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The jobGroupId property
     */
    jobGroupId?: Guid | null;
    /**
     * The jobKey property
     */
    jobKey?: ProductionJobKey | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The productionStepId property
     */
    productionStepId?: Guid | null;
    /**
     * The status property
     */
    status?: JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled | null;
    /**
     * The Type property
     */
    type?: JobProductionJob_Type | null;
}
export type JobProductionJob_Type = (typeof JobProductionJob_TypeObject)[keyof typeof JobProductionJob_TypeObject];
export type JobStatus = JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled;
export interface JobStatusCancelled extends AdditionalDataHolder, Parsable {
    /**
     * The cancelledAt property
     */
    cancelledAt?: Date | null;
    /**
     * The startedAt property
     */
    startedAt?: Date | null;
    /**
     * The Type property
     */
    type?: JobStatusCancelled_Type | null;
}
export type JobStatusCancelled_Type = (typeof JobStatusCancelled_TypeObject)[keyof typeof JobStatusCancelled_TypeObject];
export interface JobStatusDone extends AdditionalDataHolder, Parsable {
    /**
     * The completedAt property
     */
    completedAt?: Date | null;
    /**
     * The startedAt property
     */
    startedAt?: Date | null;
    /**
     * The Type property
     */
    type?: JobStatusDone_Type | null;
}
export type JobStatusDone_Type = (typeof JobStatusDone_TypeObject)[keyof typeof JobStatusDone_TypeObject];
export interface JobStatusFailed extends AdditionalDataHolder, Parsable {
    /**
     * The failedAt property
     */
    failedAt?: Date | null;
    /**
     * The reason property
     */
    reason?: string | null;
    /**
     * The startedAt property
     */
    startedAt?: Date | null;
    /**
     * The Type property
     */
    type?: JobStatusFailed_Type | null;
}
export type JobStatusFailed_Type = (typeof JobStatusFailed_TypeObject)[keyof typeof JobStatusFailed_TypeObject];
export interface JobStatusInProgress extends AdditionalDataHolder, Parsable {
    /**
     * The startedAt property
     */
    startedAt?: Date | null;
    /**
     * The Type property
     */
    type?: JobStatusInProgress_Type | null;
}
export type JobStatusInProgress_Type = (typeof JobStatusInProgress_TypeObject)[keyof typeof JobStatusInProgress_TypeObject];
export interface JobStatusObsolete extends AdditionalDataHolder, Parsable {
    /**
     * The supersedingJobId property
     */
    supersedingJobId?: Guid | null;
    /**
     * The Type property
     */
    type?: JobStatusObsolete_Type | null;
}
export type JobStatusObsolete_Type = (typeof JobStatusObsolete_TypeObject)[keyof typeof JobStatusObsolete_TypeObject];
export interface JobStatusScheduled extends AdditionalDataHolder, Parsable {
    /**
     * The Type property
     */
    type?: JobStatusScheduled_Type | null;
}
export type JobStatusScheduled_Type = (typeof JobStatusScheduled_TypeObject)[keyof typeof JobStatusScheduled_TypeObject];
export interface Pipeline extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface ProcessingJobKey extends AdditionalDataHolder, Parsable {
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The processingStepId property
     */
    processingStepId?: Guid | null;
}
export interface ProcessingStep extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The order property
     */
    order?: UntypedNode | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
}
export interface ProductionJobKey extends AdditionalDataHolder, Parsable {
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The productionStepId property
     */
    productionStepId?: Guid | null;
}
export interface ProductionStep extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
}
export interface Result extends AdditionalDataHolder, Parsable {
    /**
     * The failed property
     */
    failed?: boolean | null;
    /**
     * The problems property
     */
    problems?: ResultProblem[] | null;
    /**
     * The succeeded property
     */
    succeeded?: boolean | null;
}
export interface ResultProblem extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The exceptionSummary property
     */
    exceptionSummary?: string | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The severity property
     */
    severity?: UntypedNode | null;
    /**
     * The source property
     */
    source?: string | null;
    /**
     * The tags property
     */
    tags?: string[] | null;
}
/**
 * Serializes information the current object
 * @param ArtifactBundle The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeArtifactBundle(writer: SerializationWriter, artifactBundle: Partial<ArtifactBundle> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!artifactBundle || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", artifactBundle.createdAt);
    writer.writeGuidValue("id", artifactBundle.id);
    writer.writeGuidValue("pipelineId", artifactBundle.pipelineId);
    writer.writeNumberValue("status", artifactBundle.status);
    writer.writeAdditionalData(artifactBundle.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateProcessingStepRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateProcessingStepRequest(writer: SerializationWriter, createProcessingStepRequest: Partial<CreateProcessingStepRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createProcessingStepRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createProcessingStepRequest.name);
    writer.writeObjectValue("order", createProcessingStepRequest.order);
    writer.writeAdditionalData(createProcessingStepRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateProductionStepRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateProductionStepRequest(writer: SerializationWriter, createProductionStepRequest: Partial<CreateProductionStepRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createProductionStepRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createProductionStepRequest.name);
    writer.writeAdditionalData(createProductionStepRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateTriggerRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateTriggerRequest(writer: SerializationWriter, createTriggerRequest: Partial<CreateTriggerRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createTriggerRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createTriggerRequest.name);
    writer.writeObjectValue<TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget>("target", createTriggerRequest.target, serializeTriggerTarget);
    writer.writeAdditionalData(createTriggerRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param IdOfArtifactBundle The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIdOfArtifactBundle(writer: SerializationWriter, idOfArtifactBundle: Partial<IdOfArtifactBundle> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!idOfArtifactBundle || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(idOfArtifactBundle.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobGroupProcessingJobGroup The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobGroupProcessingJobGroup(writer: SerializationWriter, jobGroupProcessingJobGroup: Partial<JobGroupProcessingJobGroup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobGroupProcessingJobGroup || isSerializingDerivedType) { return; }
    writer.writeGuidValue("artifactBundleId", jobGroupProcessingJobGroup.artifactBundleId);
    writer.writeDateValue("createdAt", jobGroupProcessingJobGroup.createdAt);
    writer.writeGuidValue("id", jobGroupProcessingJobGroup.id);
    writer.writeGuidValue("pipelineId", jobGroupProcessingJobGroup.pipelineId);
    writer.writeGuidValue("processingStepId", jobGroupProcessingJobGroup.processingStepId);
    writer.writeEnumValue<JobGroupProcessingJobGroup_Type>("$type", jobGroupProcessingJobGroup.type);
    writer.writeAdditionalData(jobGroupProcessingJobGroup.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobGroupProductionJobGroup The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobGroupProductionJobGroup(writer: SerializationWriter, jobGroupProductionJobGroup: Partial<JobGroupProductionJobGroup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobGroupProductionJobGroup || isSerializingDerivedType) { return; }
    writer.writeGuidValue("artifactBundleId", jobGroupProductionJobGroup.artifactBundleId);
    writer.writeDateValue("createdAt", jobGroupProductionJobGroup.createdAt);
    writer.writeGuidValue("id", jobGroupProductionJobGroup.id);
    writer.writeGuidValue("pipelineId", jobGroupProductionJobGroup.pipelineId);
    writer.writeEnumValue<JobGroupProductionJobGroup_Type>("$type", jobGroupProductionJobGroup.type);
    writer.writeAdditionalData(jobGroupProductionJobGroup.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobProcessingJob The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobProcessingJob(writer: SerializationWriter, jobProcessingJob: Partial<JobProcessingJob> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobProcessingJob || isSerializingDerivedType) { return; }
    writer.writeGuidValue("artifactBundleId", jobProcessingJob.artifactBundleId);
    writer.writeDateValue("createdAt", jobProcessingJob.createdAt);
    writer.writeGuidValue("id", jobProcessingJob.id);
    writer.writeGuidValue("jobGroupId", jobProcessingJob.jobGroupId);
    writer.writeObjectValue<ProcessingJobKey>("jobKey", jobProcessingJob.jobKey, serializeProcessingJobKey);
    writer.writeGuidValue("pipelineId", jobProcessingJob.pipelineId);
    writer.writeObjectValue<JobProcessingJob_processingResultMember1 | Result>("processingResult", jobProcessingJob.processingResult, serializeJobProcessingJob_processingResult);
    writer.writeGuidValue("processingStepId", jobProcessingJob.processingStepId);
    writer.writeObjectValue<JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled>("status", jobProcessingJob.status, serializeJobStatus);
    writer.writeEnumValue<JobProcessingJob_Type>("$type", jobProcessingJob.type);
    writer.writeAdditionalData(jobProcessingJob.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobProcessingJob_processingResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobProcessingJob_processingResult(writer: SerializationWriter, jobProcessingJob_processingResult: Partial<JobProcessingJob_processingResultMember1 | Result> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeJobProcessingJob_processingResultMember1(writer, jobProcessingJob_processingResult as JobProcessingJob_processingResultMember1);
    serializeResult(writer, jobProcessingJob_processingResult as Result);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobProcessingJob_processingResultMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobProcessingJob_processingResultMember1(writer: SerializationWriter, jobProcessingJob_processingResultMember1: Partial<JobProcessingJob_processingResultMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobProcessingJob_processingResultMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(jobProcessingJob_processingResultMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobProductionJob The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobProductionJob(writer: SerializationWriter, jobProductionJob: Partial<JobProductionJob> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobProductionJob || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", jobProductionJob.createdAt);
    writer.writeGuidValue("id", jobProductionJob.id);
    writer.writeGuidValue("jobGroupId", jobProductionJob.jobGroupId);
    writer.writeObjectValue<ProductionJobKey>("jobKey", jobProductionJob.jobKey, serializeProductionJobKey);
    writer.writeGuidValue("pipelineId", jobProductionJob.pipelineId);
    writer.writeGuidValue("productionStepId", jobProductionJob.productionStepId);
    writer.writeObjectValue<JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled>("status", jobProductionJob.status, serializeJobStatus);
    writer.writeEnumValue<JobProductionJob_Type>("$type", jobProductionJob.type);
    writer.writeAdditionalData(jobProductionJob.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatus The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatus(writer: SerializationWriter, jobStatus: Partial<JobStatusCancelled | JobStatusDone | JobStatusFailed | JobStatusInProgress | JobStatusObsolete | JobStatusScheduled> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeJobStatusCancelled(writer, jobStatus as JobStatusCancelled);
    serializeJobStatusDone(writer, jobStatus as JobStatusDone);
    serializeJobStatusFailed(writer, jobStatus as JobStatusFailed);
    serializeJobStatusInProgress(writer, jobStatus as JobStatusInProgress);
    serializeJobStatusObsolete(writer, jobStatus as JobStatusObsolete);
    serializeJobStatusScheduled(writer, jobStatus as JobStatusScheduled);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatusCancelled The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatusCancelled(writer: SerializationWriter, jobStatusCancelled: Partial<JobStatusCancelled> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobStatusCancelled || isSerializingDerivedType) { return; }
    writer.writeDateValue("cancelledAt", jobStatusCancelled.cancelledAt);
    writer.writeDateValue("startedAt", jobStatusCancelled.startedAt);
    writer.writeEnumValue<JobStatusCancelled_Type>("$type", jobStatusCancelled.type);
    writer.writeAdditionalData(jobStatusCancelled.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatusDone The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatusDone(writer: SerializationWriter, jobStatusDone: Partial<JobStatusDone> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobStatusDone || isSerializingDerivedType) { return; }
    writer.writeDateValue("completedAt", jobStatusDone.completedAt);
    writer.writeDateValue("startedAt", jobStatusDone.startedAt);
    writer.writeEnumValue<JobStatusDone_Type>("$type", jobStatusDone.type);
    writer.writeAdditionalData(jobStatusDone.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatusFailed The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatusFailed(writer: SerializationWriter, jobStatusFailed: Partial<JobStatusFailed> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobStatusFailed || isSerializingDerivedType) { return; }
    writer.writeDateValue("failedAt", jobStatusFailed.failedAt);
    writer.writeStringValue("reason", jobStatusFailed.reason);
    writer.writeDateValue("startedAt", jobStatusFailed.startedAt);
    writer.writeEnumValue<JobStatusFailed_Type>("$type", jobStatusFailed.type);
    writer.writeAdditionalData(jobStatusFailed.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatusInProgress The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatusInProgress(writer: SerializationWriter, jobStatusInProgress: Partial<JobStatusInProgress> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobStatusInProgress || isSerializingDerivedType) { return; }
    writer.writeDateValue("startedAt", jobStatusInProgress.startedAt);
    writer.writeEnumValue<JobStatusInProgress_Type>("$type", jobStatusInProgress.type);
    writer.writeAdditionalData(jobStatusInProgress.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatusObsolete The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatusObsolete(writer: SerializationWriter, jobStatusObsolete: Partial<JobStatusObsolete> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobStatusObsolete || isSerializingDerivedType) { return; }
    writer.writeGuidValue("supersedingJobId", jobStatusObsolete.supersedingJobId);
    writer.writeEnumValue<JobStatusObsolete_Type>("$type", jobStatusObsolete.type);
    writer.writeAdditionalData(jobStatusObsolete.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobStatusScheduled The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobStatusScheduled(writer: SerializationWriter, jobStatusScheduled: Partial<JobStatusScheduled> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!jobStatusScheduled || isSerializingDerivedType) { return; }
    writer.writeEnumValue<JobStatusScheduled_Type>("$type", jobStatusScheduled.type);
    writer.writeAdditionalData(jobStatusScheduled.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Pipeline The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePipeline(writer: SerializationWriter, pipeline: Partial<Pipeline> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pipeline || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", pipeline.id);
    writer.writeStringValue("name", pipeline.name);
    writer.writeAdditionalData(pipeline.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProcessingJobKey The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProcessingJobKey(writer: SerializationWriter, processingJobKey: Partial<ProcessingJobKey> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!processingJobKey || isSerializingDerivedType) { return; }
    writer.writeGuidValue("pipelineId", processingJobKey.pipelineId);
    writer.writeGuidValue("processingStepId", processingJobKey.processingStepId);
    writer.writeAdditionalData(processingJobKey.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProcessingStep The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProcessingStep(writer: SerializationWriter, processingStep: Partial<ProcessingStep> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!processingStep || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", processingStep.id);
    writer.writeStringValue("name", processingStep.name);
    writer.writeObjectValue("order", processingStep.order);
    writer.writeGuidValue("pipelineId", processingStep.pipelineId);
    writer.writeAdditionalData(processingStep.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductionJobKey The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductionJobKey(writer: SerializationWriter, productionJobKey: Partial<ProductionJobKey> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productionJobKey || isSerializingDerivedType) { return; }
    writer.writeGuidValue("pipelineId", productionJobKey.pipelineId);
    writer.writeGuidValue("productionStepId", productionJobKey.productionStepId);
    writer.writeAdditionalData(productionJobKey.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductionStep The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductionStep(writer: SerializationWriter, productionStep: Partial<ProductionStep> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productionStep || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", productionStep.id);
    writer.writeStringValue("name", productionStep.name);
    writer.writeGuidValue("pipelineId", productionStep.pipelineId);
    writer.writeAdditionalData(productionStep.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Result The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResult(writer: SerializationWriter, result: Partial<Result> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!result || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("failed", result.failed);
    writer.writeCollectionOfObjectValues<ResultProblem>("problems", result.problems, serializeResultProblem);
    writer.writeBooleanValue("succeeded", result.succeeded);
    writer.writeAdditionalData(result.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ResultProblem The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResultProblem(writer: SerializationWriter, resultProblem: Partial<ResultProblem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!resultProblem || isSerializingDerivedType) { return; }
    writer.writeStringValue("exceptionSummary", resultProblem.exceptionSummary);
    writer.writeStringValue("message", resultProblem.messageEscaped);
    writer.writeObjectValue("severity", resultProblem.severity);
    writer.writeStringValue("source", resultProblem.source);
    writer.writeCollectionOfPrimitiveValues<string>("tags", resultProblem.tags);
    writer.writeAdditionalData(resultProblem.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetSecretRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetSecretRequest(writer: SerializationWriter, setSecretRequest: Partial<SetSecretRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setSecretRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("value", setSecretRequest.value);
    writer.writeAdditionalData(setSecretRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetStepConfigurationRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetStepConfigurationRequest(writer: SerializationWriter, setStepConfigurationRequest: Partial<SetStepConfigurationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setStepConfigurationRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SetStepConfigurationRequest_environmentVariables>("environmentVariables", setStepConfigurationRequest.environmentVariables, serializeSetStepConfigurationRequest_environmentVariables);
    writer.writeStringValue("image", setStepConfigurationRequest.image);
    writer.writeStringValue("script", setStepConfigurationRequest.script);
    writer.writeAdditionalData(setStepConfigurationRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SetStepConfigurationRequest_environmentVariables The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSetStepConfigurationRequest_environmentVariables(writer: SerializationWriter, setStepConfigurationRequest_environmentVariables: Partial<SetStepConfigurationRequest_environmentVariables> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!setStepConfigurationRequest_environmentVariables || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(setStepConfigurationRequest_environmentVariables.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StepConfiguration The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStepConfiguration(writer: SerializationWriter, stepConfiguration: Partial<StepConfiguration> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!stepConfiguration || isSerializingDerivedType) { return; }
    writer.writeObjectValue<StepConfiguration_environmentVariables>("environmentVariables", stepConfiguration.environmentVariables, serializeStepConfiguration_environmentVariables);
    writer.writeStringValue("image", stepConfiguration.image);
    writer.writeStringValue("script", stepConfiguration.script);
    writer.writeAdditionalData(stepConfiguration.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StepConfiguration_environmentVariables The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStepConfiguration_environmentVariables(writer: SerializationWriter, stepConfiguration_environmentVariables: Partial<StepConfiguration_environmentVariables> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!stepConfiguration_environmentVariables || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(stepConfiguration_environmentVariables.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Trigger The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTrigger(writer: SerializationWriter, trigger: Partial<Trigger> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!trigger || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", trigger.createdAt);
    writer.writeGuidValue("id", trigger.id);
    writer.writeStringValue("name", trigger.name);
    writer.writeGuidValue("pipelineId", trigger.pipelineId);
    writer.writeStringValue("secret", trigger.secret);
    writer.writeObjectValue<TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget>("target", trigger.target, serializeTriggerTarget);
    writer.writeAdditionalData(trigger.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TriggerProcessingRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTriggerProcessingRequest(writer: SerializationWriter, triggerProcessingRequest: Partial<TriggerProcessingRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!triggerProcessingRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("artifactBundleId", triggerProcessingRequest.artifactBundleId);
    writer.writeGuidValue("processingStepId", triggerProcessingRequest.processingStepId);
    writer.writeAdditionalData(triggerProcessingRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TriggerTarget The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTriggerTarget(writer: SerializationWriter, triggerTarget: Partial<TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeTriggerTargetProcessingTriggerTarget(writer, triggerTarget as TriggerTargetProcessingTriggerTarget);
    serializeTriggerTargetProductionTriggerTarget(writer, triggerTarget as TriggerTargetProductionTriggerTarget);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TriggerTargetProcessingTriggerTarget The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTriggerTargetProcessingTriggerTarget(writer: SerializationWriter, triggerTargetProcessingTriggerTarget: Partial<TriggerTargetProcessingTriggerTarget> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!triggerTargetProcessingTriggerTarget || isSerializingDerivedType) { return; }
    writer.writeGuidValue("processingStepId", triggerTargetProcessingTriggerTarget.processingStepId);
    writer.writeEnumValue<TriggerTargetProcessingTriggerTarget_Type>("$type", triggerTargetProcessingTriggerTarget.type);
    writer.writeAdditionalData(triggerTargetProcessingTriggerTarget.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TriggerTargetProductionTriggerTarget The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTriggerTargetProductionTriggerTarget(writer: SerializationWriter, triggerTargetProductionTriggerTarget: Partial<TriggerTargetProductionTriggerTarget> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!triggerTargetProductionTriggerTarget || isSerializingDerivedType) { return; }
    writer.writeEnumValue<TriggerTargetProductionTriggerTarget_Type>("$type", triggerTargetProductionTriggerTarget.type);
    writer.writeAdditionalData(triggerTargetProductionTriggerTarget.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateOrderRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateOrderRequest(writer: SerializationWriter, updateOrderRequest: Partial<UpdateOrderRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateOrderRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue("order", updateOrderRequest.order);
    writer.writeAdditionalData(updateOrderRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookRequest(writer: SerializationWriter, webhookRequest: Partial<WebhookRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookRequest || isSerializingDerivedType) { return; }
    writer.writeObjectValue<IdOfArtifactBundle | WebhookRequest_artifactBundleIdMember1>("artifactBundleId", webhookRequest.artifactBundleId, serializeWebhookRequest_artifactBundleId);
    writer.writeAdditionalData(webhookRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookRequest_artifactBundleId The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookRequest_artifactBundleId(writer: SerializationWriter, webhookRequest_artifactBundleId: Partial<IdOfArtifactBundle | WebhookRequest_artifactBundleIdMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeIdOfArtifactBundle(writer, webhookRequest_artifactBundleId as IdOfArtifactBundle);
    serializeWebhookRequest_artifactBundleIdMember1(writer, webhookRequest_artifactBundleId as WebhookRequest_artifactBundleIdMember1);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WebhookRequest_artifactBundleIdMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWebhookRequest_artifactBundleIdMember1(writer: SerializationWriter, webhookRequest_artifactBundleIdMember1: Partial<WebhookRequest_artifactBundleIdMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!webhookRequest_artifactBundleIdMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(webhookRequest_artifactBundleIdMember1.additionalData);
}
export interface SetSecretRequest extends AdditionalDataHolder, Parsable {
    /**
     * The value property
     */
    value?: string | null;
}
export interface SetStepConfigurationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The environmentVariables property
     */
    environmentVariables?: SetStepConfigurationRequest_environmentVariables | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The script property
     */
    script?: string | null;
}
export interface SetStepConfigurationRequest_environmentVariables extends AdditionalDataHolder, Parsable {
}
export interface StepConfiguration extends AdditionalDataHolder, Parsable {
    /**
     * The environmentVariables property
     */
    environmentVariables?: StepConfiguration_environmentVariables | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The script property
     */
    script?: string | null;
}
export interface StepConfiguration_environmentVariables extends AdditionalDataHolder, Parsable {
}
export interface Trigger extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The pipelineId property
     */
    pipelineId?: Guid | null;
    /**
     * The secret property
     */
    secret?: string | null;
    /**
     * The target property
     */
    target?: TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget | null;
}
export interface TriggerProcessingRequest extends AdditionalDataHolder, Parsable {
    /**
     * The artifactBundleId property
     */
    artifactBundleId?: Guid | null;
    /**
     * The processingStepId property
     */
    processingStepId?: Guid | null;
}
export type TriggerTarget = TriggerTargetProcessingTriggerTarget | TriggerTargetProductionTriggerTarget;
export interface TriggerTargetProcessingTriggerTarget extends AdditionalDataHolder, Parsable {
    /**
     * The processingStepId property
     */
    processingStepId?: Guid | null;
    /**
     * The Type property
     */
    type?: TriggerTargetProcessingTriggerTarget_Type | null;
}
export type TriggerTargetProcessingTriggerTarget_Type = (typeof TriggerTargetProcessingTriggerTarget_TypeObject)[keyof typeof TriggerTargetProcessingTriggerTarget_TypeObject];
export interface TriggerTargetProductionTriggerTarget extends AdditionalDataHolder, Parsable {
    /**
     * The Type property
     */
    type?: TriggerTargetProductionTriggerTarget_Type | null;
}
export type TriggerTargetProductionTriggerTarget_Type = (typeof TriggerTargetProductionTriggerTarget_TypeObject)[keyof typeof TriggerTargetProductionTriggerTarget_TypeObject];
export interface UpdateOrderRequest extends AdditionalDataHolder, Parsable {
    /**
     * The order property
     */
    order?: UntypedNode | null;
}
export interface WebhookRequest extends AdditionalDataHolder, Parsable {
    /**
     * The artifactBundleId property
     */
    artifactBundleId?: IdOfArtifactBundle | WebhookRequest_artifactBundleIdMember1 | null;
}
export type WebhookRequest_artifactBundleId = IdOfArtifactBundle | WebhookRequest_artifactBundleIdMember1;
export interface WebhookRequest_artifactBundleIdMember1 extends AdditionalDataHolder, Parsable {
}
export const JobGroupProcessingJobGroup_TypeObject = {
    Processing: "processing",
} as const;
export const JobGroupProductionJobGroup_TypeObject = {
    Production: "production",
} as const;
export const JobProcessingJob_TypeObject = {
    Processing: "processing",
} as const;
export const JobProductionJob_TypeObject = {
    Production: "production",
} as const;
export const JobStatusCancelled_TypeObject = {
    Cancelled: "cancelled",
} as const;
export const JobStatusDone_TypeObject = {
    Done: "done",
} as const;
export const JobStatusFailed_TypeObject = {
    Failed: "failed",
} as const;
export const JobStatusInProgress_TypeObject = {
    InProgress: "in-progress",
} as const;
export const JobStatusObsolete_TypeObject = {
    Obsolete: "obsolete",
} as const;
export const JobStatusScheduled_TypeObject = {
    Scheduled: "scheduled",
} as const;
export const TriggerTargetProcessingTriggerTarget_TypeObject = {
    Processing: "processing",
} as const;
export const TriggerTargetProductionTriggerTarget_TypeObject = {
    Production: "production",
} as const;
/* tslint:enable */
/* eslint-enable */
