/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobGroupFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type JobGroup, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/processing-steps/{stepId}/re-promote
 */
export interface RePromoteRequestBuilder extends BaseRequestBuilder<RePromoteRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobGroup>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobGroup | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RePromoteRequestBuilderUriTemplate = "{+baseurl}/api/processing-steps/{stepId}/re-promote";
/**
 * Metadata for all the requests in the request builder.
 */
export const RePromoteRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RePromoteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobGroupFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
