/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultProblemFromDiscriminatorValue, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type WithNameItemRequestBuilder, WithNameItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/secrets
 */
export interface SecretsRequestBuilder extends BaseRequestBuilder<SecretsRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesClient.api.pipelines.item.secrets.item collection
     * @param name Unique identifier of the item
     * @returns {WithNameItemRequestBuilder}
     */
     byName(name: string) : WithNameItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<string[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<string[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SecretsRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/secrets";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SecretsRequestBuilderNavigationMetadata: Record<Exclude<keyof SecretsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byName: {
        requestsMetadata: WithNameItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["name"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SecretsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SecretsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollectionOfPrimitive",
        responseBodyFactory:  "string",
    },
};
/* tslint:enable */
/* eslint-enable */
