/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithProcessingStepItemRequestBuilder, WithProcessingStepItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger/processing
 */
export interface ProcessingRequestBuilder extends BaseRequestBuilder<ProcessingRequestBuilder> {
    /**
     * Gets an item from the OlvePipelines.api.pipelines.item.trigger.processing.item collection
     * @param processingStepId Unique identifier of the item
     * @returns {WithProcessingStepItemRequestBuilder}
     */
     byProcessingStepId(processingStepId: Guid) : WithProcessingStepItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ProcessingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger/processing";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProcessingRequestBuilderNavigationMetadata: Record<Exclude<keyof ProcessingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProcessingStepId: {
        requestsMetadata: WithProcessingStepItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["processingStepId"],
    },
};
/* tslint:enable */
/* eslint-enable */
