/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobGroupFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeJobGroup, serializeTriggerProcessingRequest, type JobGroup, type ResultProblem, type TriggerProcessingRequest } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger/processing
 */
export interface ProcessingRequestBuilder extends BaseRequestBuilder<ProcessingRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobGroup>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: TriggerProcessingRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobGroup | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: TriggerProcessingRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProcessingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger/processing";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProcessingRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ProcessingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobGroupFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTriggerProcessingRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
