/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProcessingStepFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeCreateProcessingStepRequest, serializeProcessingStep, type CreateProcessingStepRequest, type ProcessingStep, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { type WithProcessingItemRequestBuilder, WithProcessingItemRequestBuilderNavigationMetadata, WithProcessingItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/processing
 */
export interface ProcessingRequestBuilder extends BaseRequestBuilder<ProcessingRequestBuilder> {
    /**
     * Gets an item from the OlvePipelines.api.pipelines.item.processing.item collection
     * @param processingId Unique identifier of the item
     * @returns {WithProcessingItemRequestBuilder}
     */
     byProcessingId(processingId: Guid) : WithProcessingItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProcessingStep[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProcessingStep[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProcessingStep>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: CreateProcessingStepRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProcessingStep | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateProcessingStepRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProcessingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/processing";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProcessingRequestBuilderNavigationMetadata: Record<Exclude<keyof ProcessingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProcessingId: {
        requestsMetadata: WithProcessingItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithProcessingItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["processingId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProcessingRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProcessingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createProcessingStepFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ProcessingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProcessingStepFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateProcessingStepRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
