/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProcessingStepFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type ProcessingStep, type ResultProblem } from '../../../../models/index.js';
// @ts-ignore
import { PromotionsRequestBuilderRequestsMetadata, type PromotionsRequestBuilder } from './promotions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/processing
 */
export interface ProcessingRequestBuilder extends BaseRequestBuilder<ProcessingRequestBuilder> {
    /**
     * The promotions property
     */
    get promotions(): PromotionsRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProcessingStep[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProcessingStep[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProcessingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/processing";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProcessingRequestBuilderNavigationMetadata: Record<Exclude<keyof ProcessingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    promotions: {
        requestsMetadata: PromotionsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProcessingRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProcessingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createProcessingStepFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
