/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { HealthRequestBuilderRequestsMetadata, type HealthRequestBuilder } from './health/index.js';
// @ts-ignore
import { PipelinesRequestBuilderNavigationMetadata, PipelinesRequestBuilderRequestsMetadata, type PipelinesRequestBuilder } from './pipelines/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The health property
     */
    get health(): HealthRequestBuilder;
    /**
     * The pipelines property
     */
    get pipelines(): PipelinesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    health: {
        requestsMetadata: HealthRequestBuilderRequestsMetadata,
    },
    pipelines: {
        requestsMetadata: PipelinesRequestBuilderRequestsMetadata,
        navigationMetadata: PipelinesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
