/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ArtifactBundlesRequestBuilderNavigationMetadata, type ArtifactBundlesRequestBuilder } from './artifactBundles/index.js';
// @ts-ignore
import { HealthRequestBuilderRequestsMetadata, type HealthRequestBuilder } from './health/index.js';
// @ts-ignore
import { JobsRequestBuilderNavigationMetadata, JobsRequestBuilderRequestsMetadata, type JobsRequestBuilder } from './jobs/index.js';
// @ts-ignore
import { PipelinesRequestBuilderNavigationMetadata, PipelinesRequestBuilderRequestsMetadata, type PipelinesRequestBuilder } from './pipelines/index.js';
// @ts-ignore
import { ProcessingStepsRequestBuilderNavigationMetadata, type ProcessingStepsRequestBuilder } from './processingSteps/index.js';
// @ts-ignore
import { ProductionStepsRequestBuilderNavigationMetadata, type ProductionStepsRequestBuilder } from './productionSteps/index.js';
// @ts-ignore
import { TriggersRequestBuilderNavigationMetadata, type TriggersRequestBuilder } from './triggers/index.js';
// @ts-ignore
import { type WebhooksRequestBuilder, WebhooksRequestBuilderNavigationMetadata } from './webhooks/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The artifactBundles property
     */
    get artifactBundles(): ArtifactBundlesRequestBuilder;
    /**
     * The health property
     */
    get health(): HealthRequestBuilder;
    /**
     * The jobs property
     */
    get jobs(): JobsRequestBuilder;
    /**
     * The pipelines property
     */
    get pipelines(): PipelinesRequestBuilder;
    /**
     * The processingSteps property
     */
    get processingSteps(): ProcessingStepsRequestBuilder;
    /**
     * The productionSteps property
     */
    get productionSteps(): ProductionStepsRequestBuilder;
    /**
     * The triggers property
     */
    get triggers(): TriggersRequestBuilder;
    /**
     * The webhooks property
     */
    get webhooks(): WebhooksRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    artifactBundles: {
        navigationMetadata: ArtifactBundlesRequestBuilderNavigationMetadata,
    },
    health: {
        requestsMetadata: HealthRequestBuilderRequestsMetadata,
    },
    jobs: {
        requestsMetadata: JobsRequestBuilderRequestsMetadata,
        navigationMetadata: JobsRequestBuilderNavigationMetadata,
    },
    pipelines: {
        requestsMetadata: PipelinesRequestBuilderRequestsMetadata,
        navigationMetadata: PipelinesRequestBuilderNavigationMetadata,
    },
    processingSteps: {
        navigationMetadata: ProcessingStepsRequestBuilderNavigationMetadata,
    },
    productionSteps: {
        navigationMetadata: ProductionStepsRequestBuilderNavigationMetadata,
    },
    triggers: {
        navigationMetadata: TriggersRequestBuilderNavigationMetadata,
    },
    webhooks: {
        navigationMetadata: WebhooksRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
