/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobGroupProcessingJobGroupFromDiscriminatorValue, createJobGroupProductionJobGroupFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, deserializeIntoJobGroupProcessingJobGroup, deserializeIntoJobGroupProductionJobGroup, serializeJobGroupProcessingJobGroup, serializeJobGroupProductionJobGroup, type JobGroupProcessingJobGroup, type JobGroupProductionJobGroup, type ResultProblem } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {JobGroupProcessingJobGroup | JobGroupProductionJobGroup}
 */
// @ts-ignore
export function createJobGroupFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoJobGroup;
}
/**
 * The deserialization information for the current model
 * @param JobGroup The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoJobGroup(jobGroup: Partial<JobGroupProcessingJobGroup | JobGroupProductionJobGroup> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoJobGroupProcessingJobGroup(jobGroup as JobGroupProcessingJobGroup),
        ...deserializeIntoJobGroupProductionJobGroup(jobGroup as JobGroupProductionJobGroup),
    }
}
export type JobGroup = JobGroupProcessingJobGroup | JobGroupProductionJobGroup;
/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger/production
 */
export interface ProductionRequestBuilder extends BaseRequestBuilder<ProductionRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobGroupProcessingJobGroup | JobGroupProductionJobGroup>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobGroupProcessingJobGroup | JobGroupProductionJobGroup | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param JobGroup The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeJobGroup(writer: SerializationWriter, jobGroup: Partial<JobGroupProcessingJobGroup | JobGroupProductionJobGroup> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeJobGroupProcessingJobGroup(writer, jobGroup as JobGroupProcessingJobGroup);
    serializeJobGroupProductionJobGroup(writer, jobGroup as JobGroupProductionJobGroup);
}
/**
 * Uri template for the request builder.
 */
export const ProductionRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger/production";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProductionRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ProductionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobGroupFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
