/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createJobGroupFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type JobGroup, type ResultProblem } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger/production
 */
export interface ProductionRequestBuilder extends BaseRequestBuilder<ProductionRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<JobGroup>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<JobGroup | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProductionRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger/production";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProductionRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ProductionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createJobGroupFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
