/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultProblemFromDiscriminatorValue, createVerificationFromDiscriminatorValue, serializeCreateVerificationRequest, serializeVerification, type CreateVerificationRequest, type ResultProblem, type Verification } from '../../../../../../models/index.js';
// @ts-ignore
import { type WithVerificationItemRequestBuilder, WithVerificationItemRequestBuilderNavigationMetadata, WithVerificationItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/processing/{processingId}/verifications
 */
export interface VerificationsRequestBuilder extends BaseRequestBuilder<VerificationsRequestBuilder> {
    /**
     * Gets an item from the OlvePipelines.api.pipelines.item.processing.item.verifications.item collection
     * @param verificationId Unique identifier of the item
     * @returns {WithVerificationItemRequestBuilder}
     */
     byVerificationId(verificationId: Guid) : WithVerificationItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Verification[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Verification[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Verification>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: CreateVerificationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Verification | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateVerificationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VerificationsRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/processing/{processingId}/verifications";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VerificationsRequestBuilderNavigationMetadata: Record<Exclude<keyof VerificationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byVerificationId: {
        requestsMetadata: WithVerificationItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithVerificationItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["verificationId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VerificationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VerificationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createVerificationFromDiscriminatorValue,
    },
    post: {
        uriTemplate: VerificationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVerificationFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateVerificationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
