/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FrontendRequestBuilderRequestsMetadata, type FrontendRequestBuilder } from './frontend/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/config
 */
export interface ConfigRequestBuilder extends BaseRequestBuilder<ConfigRequestBuilder> {
    /**
     * The frontend property
     */
    get frontend(): FrontendRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConfigRequestBuilderUriTemplate = "{+baseurl}/api/config";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConfigRequestBuilderNavigationMetadata: Record<Exclude<keyof ConfigRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    frontend: {
        requestsMetadata: FrontendRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
