/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProcessingStepFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializeProcessingStep, serializeUpdateOrderRequest, type ProcessingStep, type ResultProblem, type UpdateOrderRequest } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/processing-steps/{stepId}/order
 */
export interface OrderRequestBuilder extends BaseRequestBuilder<OrderRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProcessingStep>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     put(body: UpdateOrderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProcessingStep | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateOrderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrderRequestBuilderUriTemplate = "{+baseurl}/api/processing-steps/{stepId}/order";
/**
 * Metadata for all the requests in the request builder.
 */
export const OrderRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: OrderRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProcessingStepFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateOrderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
