/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type Pipeline, type ResultProblem } from '../../models/index.js';
// @ts-ignore
import { ItemRequestBuilderNavigationMetadata, ItemRequestBuilderRequestsMetadata, type ItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines
 */
export interface PipelinesRequestBuilder extends BaseRequestBuilder<PipelinesRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesClient.api.pipelines.item collection
     * @param id Unique identifier of the item
     * @returns {ItemRequestBuilder}
     */
     byId(id: string) : ItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Pipeline[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Pipeline[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Pipeline>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<PipelinesRequestBuilderPostQueryParameters> | undefined) : Promise<Pipeline | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<PipelinesRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface PipelinesRequestBuilderPostQueryParameters {
    name?: string;
}
/**
 * Uri template for the request builder.
 */
export const PipelinesRequestBuilderUriTemplate = "{+baseurl}/api/pipelines?name={name}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PipelinesRequestBuilderNavigationMetadata: Record<Exclude<keyof PipelinesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ItemRequestBuilderRequestsMetadata,
        navigationMetadata: ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["%2Did"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PipelinesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PipelinesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPipelineFromDiscriminatorValue,
    },
    post: {
        uriTemplate: PipelinesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
