/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTriggerItemRequestBuilder, WithTriggerItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/webhooks/github
 */
export interface GithubRequestBuilder extends BaseRequestBuilder<GithubRequestBuilder> {
    /**
     * Gets an item from the OlvePipelinesClient.api.webhooks.github.item collection
     * @param triggerId Unique identifier of the item
     * @returns {WithTriggerItemRequestBuilder}
     */
     byTriggerId(triggerId: string) : WithTriggerItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GithubRequestBuilderUriTemplate = "{+baseurl}/api/webhooks/github";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GithubRequestBuilderNavigationMetadata: Record<Exclude<keyof GithubRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTriggerId: {
        requestsMetadata: WithTriggerItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["triggerId"],
    },
};
/* tslint:enable */
/* eslint-enable */
