/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResultProblemFromDiscriminatorValue, createStepPromotionStateFromDiscriminatorValue, type ResultProblem, type StepPromotionState } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/processing/promotions
 */
export interface PromotionsRequestBuilder extends BaseRequestBuilder<PromotionsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<StepPromotionState[]>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<StepPromotionState[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PromotionsRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/processing/promotions";
/**
 * Metadata for all the requests in the request builder.
 */
export const PromotionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PromotionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createStepPromotionStateFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
