/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProductionStepFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type ProductionStep, type ResultProblem } from '../../../models/index.js';
// @ts-ignore
import { ConfigurationRequestBuilderRequestsMetadata, type ConfigurationRequestBuilder } from './configuration/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/production-steps/{stepId}
 */
export interface WithStepItemRequestBuilder extends BaseRequestBuilder<WithStepItemRequestBuilder> {
    /**
     * The configuration property
     */
    get configuration(): ConfigurationRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProductionStep>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProductionStep | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithStepItemRequestBuilderUriTemplate = "{+baseurl}/api/production-steps/{stepId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithStepItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithStepItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    configuration: {
        requestsMetadata: ConfigurationRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithStepItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithStepItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: WithStepItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProductionStepFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
