/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type Pipeline, type ResultProblem } from '../../../models/index.js';
// @ts-ignore
import { ArtifactBundlesRequestBuilderRequestsMetadata, type ArtifactBundlesRequestBuilder } from './artifactBundles/index.js';
// @ts-ignore
import { BindingRequestBuilderNavigationMetadata, BindingRequestBuilderRequestsMetadata, type BindingRequestBuilder } from './binding/index.js';
// @ts-ignore
import { DocumentRequestBuilderRequestsMetadata, type DocumentRequestBuilder } from './document/index.js';
// @ts-ignore
import { ProcessingRequestBuilderNavigationMetadata, ProcessingRequestBuilderRequestsMetadata, type ProcessingRequestBuilder } from './processing/index.js';
// @ts-ignore
import { ProductionRequestBuilderRequestsMetadata, type ProductionRequestBuilder } from './production/index.js';
// @ts-ignore
import { SecretsRequestBuilderNavigationMetadata, SecretsRequestBuilderRequestsMetadata, type SecretsRequestBuilder } from './secrets/index.js';
// @ts-ignore
import { TriggerRequestBuilderNavigationMetadata, type TriggerRequestBuilder } from './trigger/index.js';
// @ts-ignore
import { TriggersRequestBuilderRequestsMetadata, type TriggersRequestBuilder } from './triggers/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}
 */
export interface ItemRequestBuilder extends BaseRequestBuilder<ItemRequestBuilder> {
    /**
     * The artifactBundles property
     */
    get artifactBundles(): ArtifactBundlesRequestBuilder;
    /**
     * The binding property
     */
    get binding(): BindingRequestBuilder;
    /**
     * The document property
     */
    get document(): DocumentRequestBuilder;
    /**
     * The processing property
     */
    get processing(): ProcessingRequestBuilder;
    /**
     * The production property
     */
    get production(): ProductionRequestBuilder;
    /**
     * The secrets property
     */
    get secrets(): SecretsRequestBuilder;
    /**
     * The trigger property
     */
    get trigger(): TriggerRequestBuilder;
    /**
     * The triggers property
     */
    get triggers(): TriggersRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Pipeline>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Pipeline | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ItemRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    artifactBundles: {
        requestsMetadata: ArtifactBundlesRequestBuilderRequestsMetadata,
    },
    binding: {
        requestsMetadata: BindingRequestBuilderRequestsMetadata,
        navigationMetadata: BindingRequestBuilderNavigationMetadata,
    },
    document: {
        requestsMetadata: DocumentRequestBuilderRequestsMetadata,
    },
    processing: {
        requestsMetadata: ProcessingRequestBuilderRequestsMetadata,
        navigationMetadata: ProcessingRequestBuilderNavigationMetadata,
    },
    production: {
        requestsMetadata: ProductionRequestBuilderRequestsMetadata,
    },
    secrets: {
        requestsMetadata: SecretsRequestBuilderRequestsMetadata,
        navigationMetadata: SecretsRequestBuilderNavigationMetadata,
    },
    trigger: {
        navigationMetadata: TriggerRequestBuilderNavigationMetadata,
    },
    triggers: {
        requestsMetadata: TriggersRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
