/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createArtifactBundleFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type ArtifactBundle, type ResultProblem } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/trigger/building
 */
export interface BuildingRequestBuilder extends BaseRequestBuilder<BuildingRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArtifactBundle>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArtifactBundle | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BuildingRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/trigger/building";
/**
 * Metadata for all the requests in the request builder.
 */
export const BuildingRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BuildingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createArtifactBundleFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
