/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineDocumentFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, serializePipelineDocument, type PipelineDocument, type ResultProblem } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/from-document
 */
export interface FromDocumentRequestBuilder extends BaseRequestBuilder<FromDocumentRequestBuilder> {
    /**
     * @param body Beta: shape may change within the 0.x major version.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineDocument>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     post(body: PipelineDocument, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineDocument | undefined>;
    /**
     * @param body Beta: shape may change within the 0.x major version.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PipelineDocument, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FromDocumentRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/from-document";
/**
 * Metadata for all the requests in the request builder.
 */
export const FromDocumentRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: FromDocumentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineDocumentFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePipelineDocument,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
