/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPipelineSourceFromDiscriminatorValue, createResultProblemFromDiscriminatorValue, type PipelineSource, type ResultProblem } from '../../../../../models/index.js';
// @ts-ignore
import { GithubRequestBuilderRequestsMetadata, type GithubRequestBuilder } from './github/index.js';
// @ts-ignore
import { HardcodedRequestBuilderRequestsMetadata, type HardcodedRequestBuilder } from './hardcoded/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/pipelines/{-id}/sources/{sourceId}
 */
export interface WithSourceItemRequestBuilder extends BaseRequestBuilder<WithSourceItemRequestBuilder> {
    /**
     * The github property
     */
    get github(): GithubRequestBuilder;
    /**
     * The hardcoded property
     */
    get hardcoded(): HardcodedRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PipelineSource>}
     * @throws {ResultProblem} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PipelineSource | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithSourceItemRequestBuilderUriTemplate = "{+baseurl}/api/pipelines/{%2Did}/sources/{sourceId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithSourceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithSourceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    github: {
        requestsMetadata: GithubRequestBuilderRequestsMetadata,
    },
    hardcoded: {
        requestsMetadata: HardcodedRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithSourceItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithSourceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: WithSourceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createResultProblemFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPipelineSourceFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
